import type { MotherLang } from "@/lib/mother-copy";

const KITCHEN: Record<string, { ta: string; hi: string }> = {
  "ragi dosa with coconut chutney": { ta: "ராகி தோசை தேங்காய் சட்னி", hi: "रागी डोसा नारियल चटनी" },
  "idli with vegetable sambar": { ta: "இட்லி காய்கறி சாம்பார்", hi: "इडली सब्ज़ी सांभर" },
  "pongal with sambar": { ta: "பொங்கல் சாம்பார்", hi: "पोंगल सांभर" },
  "paneer paratha with curd": { ta: "பனீர் பராத்தா தயிர்", hi: "पनीर पराठा दही" },
  "vegetable upma with peanuts": { ta: "காய்கறி உப்புமா வேர்க்கடலை", hi: "सब्ज़ी उपमा मूंगफली" },
  "moong dal khichdi with ghee": { ta: "பாசிப்பயறு கிச்சடி நெய்", hi: "मूंग दाल खिचड़ी घी" },
  "plain moong khichdi": { ta: "பாசிப்பயறு கிச்சடி", hi: "मूंग खिचड़ी" },
  "rajma rice with salad": { ta: "ராஜ்மா சாதம் சாலட்", hi: "राजमा चावल सलाद" },
  "sambar rice with poriyal": { ta: "சாம்பார் சாதம் பொரியல்", hi: "सांभर चावल पोरियल" },
  "paneer tikka wrap": { ta: "பனீர் திக்கா ரேப்", hi: "पनीर टिक्का रैप" },
  "chickpea chole with jeera rice": { ta: "கொண்டைக்கடலை சோளே சீரக சாதம்", hi: "चने छोले जीरा राइस" },
  "egg bhurji with multigrain toast": { ta: "முட்டை புர்ஜி மல்டிகிரெயின் டோஸ்ட்", hi: "अंडा भुर्जी मल्टीग्रेन टोस्ट" },
  "boiled eggs with vegetable poha": { ta: "வேகவைத்த முட்டை காய்கறி பொஹா", hi: "उबले अंडे सब्ज़ी पोहा" },
  "vegetable poha": { ta: "காய்கறி பொஹா", hi: "सब्ज़ी पोहा" },
  "grilled chicken tikka with roti": { ta: "கிரில் சிக்கன் திக்கா ரொட்டி", hi: "ग्रिल्ड चिकन टिक्का रोटी" },
  "chicken stew with appam": { ta: "சிக்கன் ஸ்டூ அப்பம்", hi: "चिकन स्टू अप्पम" },
  "banana almond smoothie": { ta: "வாழை பாதாம் ஸ்மூத்தி", hi: "केला बादाम स्मूदी" },
  "banana oat smoothie with soy milk": { ta: "வாழை ஓட் ஸ்மூத்தி சோயா பால்", hi: "केला ओट स्मूदी सोया दूध" },
  "sprouts chaat with pomegranate": { ta: "முளை சாட் மாதுளை", hi: "अंकुर चाट अनार" },
  "roasted chana and fruit cup": { ta: "வறுத்த கடலை பழக் கிண்ணம்", hi: "भुना चना और फल" },
  "vegetable pulao with raita": { ta: "காய்கறி புலாவ் ராய்த்தா", hi: "सब्ज़ी पुलाव रायता" },
  "vegetable pulao with cucumber salad": { ta: "காய்கறி புலாவ் வெள்ளரி சாலட்", hi: "सब्ज़ी पुलाव खीरा सलाद" },
  "curd rice with pickle": { ta: "தயிர் சாதம் ஊறுகாய்", hi: "दही चावल अचार" },
  "lemon rice with beans poriyal": { ta: "எலுமிச்சை சாதம் பீன்ஸ் பொரியல்", hi: "नींबू चावल बीन्स पोरियल" },
  "masala oats with nuts": { ta: "மசாலா ஓட்ஸ் கொட்டைகள்", hi: "मसाला ओट्स मेवे" },
  "savory vegetable oats": { ta: "காய்கறி ஓட்ஸ்", hi: "सब्ज़ी ओट्स" },
  "ragi porridge with jaggery": { ta: "ராகி கஞ்சி வெல்லம்", hi: "रागी दलिया गुड़" },
  "dalia with milk and dates": { ta: "கோதுமை ரவை பால் பேரிச்சை", hi: "दलिया दूध और खजूर" },
  "paneer dosa": { ta: "பனீர் தோசை", hi: "पनीर डोसा" },
  "masala dosa with potato filling": { ta: "மசாலா தோசை உருளைக்கிழங்கு", hi: "मसाला डोसा आलू" },
  "mixed veg paratha with pickle": { ta: "காய்கறி பராத்தா ஊறுகாய்", hi: "मिक्स्ड वेज पराठा अचार" },
  "bajra roti with mixed vegetable sabzi": { ta: "கம்பு ரொட்டி காய்கறி சப்ஜி", hi: "बाजरा रोटी मिक्स सब्ज़ी" },
  "fruit and nut energy bowl": { ta: "பழம் கொட்டை கிண்ணம்", hi: "फल और मेवे का कटोरा" },
  "seasonal fruit bowl": { ta: "பருவ பழக் கிண்ணம்", hi: "मौसमी फल कटोरा" },
  "fish curry with rice": { ta: "மீன் குழம்பு சாதம்", hi: "मछली करी चावल" },
  "tofu bhurji with millet roti": { ta: "டோஃபு புர்ஜி சிறுதானிய ரொட்டி", hi: "टोफू भुर्जी मिलेट रोटी" },
  "palak dal with rice": { ta: "கீரை பருப்பு சாதம்", hi: "पालक दाल चावल" },
  "besan cheela with mint chutney": { ta: "கடலை மாவு தோசை புதினா சட்னி", hi: "बेसन चीला पुदीना चटनी" },
  "coconut rice with cabbage thoran": { ta: "தேங்காய் சாதம் முட்டைகோஸ் தொரன்", hi: "नारियल चावल पत्तागोभी थोरन" },
  "tomato rasam rice with beans poriyal": { ta: "தக்காளி ரசம் சாதம் பீன்ஸ் பொரியல்", hi: "टमाटर रसम चावल बीन्स पोरियल" },
  "vegetable kootu with steamed rice": { ta: "காய்கறி கூட்டு சாதம்", hi: "सब्ज़ी कूटू भात" },
  "onion uttapam with sambar": { ta: "வெங்காய உத்தப்பம் சாம்பார்", hi: "प्याज़ उत्तपम सांभर" },
  "egg dosa with tomato chutney": { ta: "முட்டை தோசை தக்காளி சட்னி", hi: "अंडा डोसा टमाटर चटनी" },
  "mild fish fry with lemon rice": { ta: "மீன் வறுவல் எலுமிச்சை சாதம்", hi: "हल्की मछली फ्राई नींबू चावल" },
  "keerai masiyal with rice": { ta: "கீரை மசியல் சாதம்", hi: "कीराई मसियाल चावल" },
  "boiled peanut sundal": { ta: "வேர்க்கடலை சுண்டல்", hi: "उबला मूंगफली सुंडल" },
  "steamed rice with moong dal and vegetables": { ta: "சாதம் பாசிப்பயறு காய்கறி", hi: "भात मूंग दाल सब्ज़ी" },
  "ragi dosa": { ta: "ராகி தோசை", hi: "रागी डोसा" },
  idli: { ta: "இட்லி", hi: "इडली" },
  sambar: { ta: "சாம்பார்", hi: "सांभर" },
  "lemon rice": { ta: "எலுமிச்சை சாதம்", hi: "नींबू चावल" },
  "masala dosa": { ta: "மசாலா தோசை", hi: "मसाला डोसा" },
  "moong khichdi": { ta: "பாசிப்பயறு கிச்சடி", hi: "मूंग खिचड़ी" },
  "rajma rice": { ta: "ராஜ்மா சாதம்", hi: "राजमा चावल" },
  "vegetable pulao": { ta: "காய்கறி புலாவ்", hi: "सब्ज़ी पुलाव" },
  "besan cheela": { ta: "கடலை மாவு தோசை", hi: "बेसन चीला" },
  "palak dal": { ta: "கீரை பருப்பு", hi: "पालक दाल" },
  "sprouts chaat": { ta: "முளை சாட்", hi: "अंकुर चाट" },
  "ragi porridge": { ta: "ராகி கஞ்சி", hi: "रागी दलिया" },
  "mild chicken stew": { ta: "சிக்கன் ஸ்டூ", hi: "हल्का चिकन स्टू" },
  "moong dal": { ta: "பாசிப்பயறு பருப்பு", hi: "मूंग दाल" },
  chole: { ta: "சோளே", hi: "छोले" },
  "ragi flour": { ta: "ராகி மாவு", hi: "रागी आटा" },
  "idli / dosa batter": { ta: "இட்லி / தோசை மாவு", hi: "इडली / डोसा घोल" },
  coconut: { ta: "தேங்காய்", hi: "नारियल" },
  oats: { ta: "ஓட்ஸ்", hi: "ओट्स" },
  bananas: { ta: "வாழைப்பழம்", hi: "केले" },
  paneer: { ta: "பனீர்", hi: "पनीर" },
  dal: { ta: "பருப்பு", hi: "दाल" },
  rice: { ta: "சாதம்", hi: "चावल" },
  fish: { ta: "மீன்", hi: "मछली" },
  eggs: { ta: "முட்டை", hi: "अंडे" },
  curd: { ta: "தயிர்", hi: "दही" },
  milk: { ta: "பால்", hi: "दूध" },
  palak: { ta: "கீரை", hi: "पालक" },
  tomatoes: { ta: "தக்காளி", hi: "टमाटर" },
  "mixed vegetables": { ta: "கலப்பு காய்கறி", hi: "मिक्स्ड सब्ज़ी" },
  monday: { ta: "திங்கள்", hi: "सोमवार" },
  tuesday: { ta: "செவ்வாய்", hi: "मंगलवार" },
  wednesday: { ta: "புதன்", hi: "बुधवार" },
  thursday: { ta: "வியாழன்", hi: "गुरुवार" },
  friday: { ta: "வெள்ளி", hi: "शुक्रवार" },
  saturday: { ta: "சனி", hi: "शनिवार" },
  sunday: { ta: "ஞாயிறு", hi: "रविवार" },
};

export function translateKitchen(lang: MotherLang, text: string): string {
  if (lang === "en" || !text) return text;
  const hit = KITCHEN[text.trim().toLowerCase()];
  return hit ? hit[lang] : text;
}
