import type { MealSlot } from "@/types/babybite";

export type MotherLang = "en" | "ta" | "hi";

export const MOTHER_LANGS: { id: MotherLang; short: string; label: string }[] = [
  { id: "en", short: "EN", label: "English" },
  { id: "ta", short: "த", label: "Tamil" },
  { id: "hi", short: "हिं", label: "Hindi" },
];

const COPY = {
  en: {
    makePlan: "Make a plan for my child",
    haveAccount: "I already have an account",
    seeHow: "See how it looks",
    tonight: "Tonight",
    forYou: "For you",
    also: "Also",
    later: "Later",
    you: "You",
    signIn: "Sign in",
    childKitchen: "Child & kitchen",
    showThirty: "Show my 30 days",
    openTonight: "Open tonight’s meals",
    continueChild: "Continue your child’s details",
    fridgePdf: "Get the fridge PDF",
    whatsapp: "Send on WhatsApp",
    grocery: "Keep at home today",
    dinnerIs: "Dinner",
    breakfast: "Breakfast",
    lunch: "Lunch",
    snack: "Snack",
    sampleCaption: "Indian meals for mothers of kids 4–12",
    sampleFor: "For a 7-year-old. South Indian kitchen.",
    writingDinner: "Writing tonight’s plate…",
    planReady: "Tonight is ready",
    table: "Table",
    why: "Why",
    whatsDinner: "What’s for dinner?",
    ourPlates: "The plates",
    howTitle: "How dinner gets decided",
    step1: "Tell us how you cook",
    step1Body: "Age 4–12, kitchen, allergies. Five minutes. Then we stay in your home food.",
    step2: "Tonight is written",
    step2Body: "Breakfast through dinner, rotated so the table does not repeat itself.",
    step3: "Tape the fridge PDF",
    step3Body: "Thirty days on paper. WhatsApp tonight. No 7pm question.",
    noSeven: "No 7pm question",
    bandBody: "Thirty days of Indian meals. Tape the fridge. WhatsApp tonight.",
    footerTag: "For mothers of kids 4–12",
    duoKicker: "From the kitchen",
    duoTitle: "Breakfast, then lunch",
    bondKicker: "Mother and child",
    bondTitle: "Dinner is how you hold them",
    bondBody:
      "After school, the question is always the same. BabyBite writes the plate so you can sit down, look at them, and eat together.",
    bondTag: "We eat together",
    menuTag: "Indian meals for mothers of kids 4–12.",
    stickerTonight: "Tonight",
    stickerAges: "Ages 4–12",
    stickerKitchen: "Indian kitchen",
    stickerFridge: "Fridge PDF",
    stickerSimple: "Keep it simple",
    stickerProtein: "Protein",
    stickerPicky: "Picky eater?",
    stickerSchool: "School tiffin",
    stickerSeven: "7pm, sorted",
    stickerGrains: "Ragi · Dal · Curd",
    stickerRegion: "South · North · Mixed",
    stickerDinnerQ: "What’s for dinner?",
    benefitKicker: "Why mothers stay",
    benefitTitle: "Help at the table — not a menu to guess",
    benefitThirty: "30 days, already written",
    benefitChecklist: "From your kitchen answers",
    benefitNoGuess: "No guessing at 7pm",
    benefitTiffin: "A school box that travels",
    benefitPdf: "PDF on the fridge",
    benefitPicky: "Help for picky eaters",
    benefitProtein: "Protein without a fight",
    benefitAges: "Made for ages 4–12",
    welcomeBack: "Welcome back",
    createAccount: "Create your account",
    authNote: "Indian plates for mothers of kids 4–12.",
    fullName: "Full name",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm password",
    passwordHint: "8+ characters with letters and numbers",
    createAccountBtn: "Create account",
    creating: "Creating…",
    signingIn: "Signing in…",
    or: "Or",
    continueGoogle: "Continue with Google",
    reviewTerms: "Review Terms & Conditions",
    haveAccountQ: "Have an account?",
    noAccount: "No account?",
    createOne: "Create one",
    acceptedTermsNote:
      "You accepted our Terms & Conditions (education only — consult your doctor for medical decisions).",
    termsTitle: "Terms & Conditions",
    termsSub: "For mothers of kids 4–12",
    termsRequired: "Required before signup",
    termsScroll: "Scroll to the bottom to continue",
    termsDecline: "Decline",
    termsAgree: "I agree — create account",
    termsVersion: "Version",
    closeMenu: "Close menu",
    openMenu: "Open menu",
    language: "Language",
    obTitle1: "Your child next to other kids",
    obTitle2: "How you cook at home",
    obTitleKitchen: "What is true in the kitchen tonight",
    obTitle3: "What feels hard at the table",
    obTitle4: "What you want this month",
    obTitle5: "We’ll build from this",
    obLede1: "Name, age, then height and weight. That comparison is why most mothers open this. We show the usual band for ages 4–12. The plate feeds growing — we do not promise extra centimetres.",
    obLede2: "Vegetarian, eggs, or non-veg; South, North, or mixed. We stay in your kitchen.",
    obLedeKitchen: "Ten minutes or a full cook. Tight money or normal. Rice or no rice. School tiffin or home only.",
    obLede3: "Picky eating, skipped vegetables, low energy: tick what is true this month.",
    obLede4: "One focus for the next 30 days. The PDF and the meals follow this choice.",
    obLede5: "Check the picture. Next we read the table — then tonight’s plates and the fridge PDF.",
    roomChild: "Child",
    roomFood: "Food",
    roomKitchen: "Tonight",
    roomChallenges: "Challenges",
    roomGoal: "Goal",
    roomReview: "Review",
    cookTime: "How much time tonight",
    cookTenMin: "10 minutes",
    cookNormal: "I can cook",
    cookTenMinHint: "Evening snacks and plates that are ready before they ask again.",
    cookNormalHint: "A normal Indian cook — dosa, dal, sabzi.",
    kitchenMoney: "The grocery box",
    budgetTight: "Keep it cheap",
    budgetNormal: "Normal",
    budgetTightHint: "Dal, chana, banana, roti. What is already at home.",
    budgetNormalHint: "Paneer or fish can sit on some days.",
    kitchenRice: "Rice at the table",
    riceEats: "Eats rice",
    riceRefuses: "No rice tonight",
    riceEatsHint: "Sambar rice, pulao, dal-rice can stay.",
    riceRefusesHint: "Roti, dosa, poha, millets instead of plated rice.",
    kitchenTiffin: "School tiffin",
    tiffinSchool: "School tiffin",
    tiffinHome: "Home only",
    tiffinSchoolHint: "A box that travels — wrap, paratha, idli, poha.",
    tiffinHomeHint: "Lunch is at the home table.",
    roomByMeal: "By meal",
    roomByProblem: "By problem",
    roomBrowseKicker: "Each opens a menu of ideas below",
    roomHasMoreLists: "Opens list options below",
    roomPlanLabel: "Calendar",
    roomBrowseLabel: "Kitchen lists",
    roomBrowseMealHint: "Breakfast, lunch, dinner & snacks",
    roomBrowseProblemHint: "Time, budget, tiffin & picky eaters",
    roomCaptionToday: "Five meals for today",
    roomCaptionWeek: "Your week at a glance",
    roomCaptionMonth: "30 days — tap a day to open",
    roomCaptionTiffin: "Weekday lunch boxes",
    roomCaptionMeals: "Ideas grouped by meal time",
    roomCaptionProblems: "Ideas grouped by what you need",
    roomTiffin: "Tiffin week",
    plateAges45: "Ages 4–5 plate",
    plateAges68: "Ages 6–8 plate",
    plateAges912: "Ages 9–12 plate",
    sameLunchNote: "Same lunch is showing up — here are box alternatives.",
    tiffinWeekHint: "Weekday lunch packed for school. Swap if they refuse the box.",
    schoolFilter: "Box Lunch Swap",
    boxLunchSwapTitle: "Box Lunch Swap",
    boxLunchSwapLead: "Change your child’s packable lunch for this day.",
    todaysPackableLunch: "Today’s Packable Lunch",
    packableLunch: "Packable Lunch",
    packableBadge: "School box · travels well",
    swapWithLabel: "Swap with",
    selectMeal: "Select",
    selectedMeal: "Selected",
    viewMealDetails: "View meal",
    confirmLunchSwap: "Confirm Lunch Swap",
    lunchSwapUpdated: "Packable lunch updated!",
    lunchSwapFailed: "Couldn’t update the lunch. Please try again.",
    schoolFilterHint: "Today & week show packable lunches you can send in a tiffin box.",
    checklistBuilt: "Built from your checklist",
    funnelRerouteHint: "You skipped a step — we kept your place. Continue here:",
    whyThisPlate: "Why this plate",
    schoolFilterEmpty: "No packable lunches in this kitchen yet. Try another list or regenerate your plan.",
    listBreakfast: "Breakfast",
    listLunch: "Lunch",
    listDinner: "Dinner",
    listSnacks: "Snacks",
    listTenMin: "10-min food",
    listBudget: "Budget food",
    listSchool: "School tiffin",
    listFavourite: "Kids’ favourite",
    listNoRice: "No rice",
    listHomemade: "Homemade snacks",
    kitchenPickMeal: "Pick a meal list",
    kitchenPickProblem: "What do you need help with?",
    kitchenIdeasCount: "ideas in this list",
    kitchenListCount: "lists",
    hintListBreakfast: "Morning plates before school",
    hintListLunch: "Packable lunches for school days",
    hintListDinner: "Evening food for the whole table",
    hintListSnacks: "Small bites between meals",
    hintListTenMin: "When the clock is tight",
    hintListBudget: "Kind to your weekly spend",
    hintListSchool: "Box-friendly lunch ideas",
    hintListFavourite: "Picky eaters and crowd pleasers",
    hintListNoRice: "Plates without rice",
    hintListHomemade: "From your kitchen, not the packet",
    ifTheyRefuse: "If they refuse this",
    minutesWord: "minutes",
    pantryLine: "From the box",
    familyPotNote: "Same pot, milder for the child.",
    kitchenLine: "Quick evening snacks, rice alternatives, and 10-minute food from what is already at home.",
    emptyKitchenList: "Nothing in this list for this kitchen yet. Try another problem.",
    snacksThisWeek: "Snacks this week",
    stepOf: "Step",
    of: "of",
    field: "Field",
    yourAnswer: "Your answer",
    name: "Name",
    age: "Age",
    gender: "Gender",
    boy: "Boy",
    girl: "Girl",
    other: "Other",
    ageRange: "4–12 years only",
    genderHint: "Boy or girl",
    optionalHw: "Height & weight — the comparison",
    hwMain: "The park comparison",
    hwLede: "Other children the same age can look taller or heavier. Note your child's height and weight. See the usual band. Then we write plates for energy, protein, and calcium.",
    hwBand: "Usual for this age",
    hwSkip: "No tape today? Leave blank and add it later.",
    heightCm: "Height cm",
    weightKg: "Weight kg",
    anyAllergies: "Any allergies? (optional)",
    foodsAvoid: "Foods to avoid (optional)",
    foodsAvoidPh: "e.g. mushroom, bitter gourd",
    namePh: "e.g. Aanya, Rohan…",
    choice: "Choice",
    now: "Now",
    diet: "Diet",
    style: "Style",
    dietHome: "Diet at home",
    regionStyle: "Regional style",
    veg: "Vegetarian",
    egg: "Eggetarian",
    nonveg: "Non-veg",
    south: "South Indian",
    north: "North Indian",
    mixed: "Mixed",
    vegHint: "Plant-based meals",
    eggHint: "Includes eggs",
    nonvegHint: "Includes meat",
    southHint: "Dosa, sambar, rice",
    northHint: "Roti, paratha, dal",
    mixedHint: "Best of both",
    challengeTick: "Tick everything that is true at your table this month. More than one is fine.",
    pickyHint: "Refuses new foods",
    underHint: "Needs more calories",
    vegSkipHint: "Skips veggies",
    readyFor: "Ready for",
    seeTable: "See the table",
    continue: "Continue",
    back: "Back",
    saving: "Saving…",
    yourChild: "Your child",
    years: "years",
    enterName: "Enter your child's name",
    pickChallenge: "Pick at least one challenge",
    selectChallenge: "Select at least one challenge",
    signInToSave: "Sign in to save your profile",
    nextReadTable: "Next we put your child next to the usual height and weight band. Then tonight’s plates and the fridge PDF.",
    allergyDairy: "Dairy",
    allergyNuts: "Tree nuts",
    allergyEggs: "Eggs",
    allergyGluten: "Gluten / wheat",
    allergySoy: "Soy",
    allergySeafood: "Fish / seafood",
    chUnder: "Underweight",
    chAppetite: "Poor appetite",
    chPicky: "Picky eater",
    chVeg: "Doesn't like vegetables",
    chMilk: "Doesn't drink milk",
    chEnergy: "Low energy",
    chSports: "Active sports child",
    goalHealthy: "Healthy nutrition",
    goalHabits: "Better eating habits",
    goalProtein: "Protein focus",
    goalBalance: "Balanced meals",
    goalVariety: "Improved food variety",
    roomToday: "Today",
    roomWeek: "This week",
    roomMonth: "30 days",
    monthHint: "One lunch per day. Tap a day for breakfast through dinner.",
    roomGoals: "Goals",
    morningSnack: "Morning snack",
    eveningSnack: "Evening snack",
    kcal: "kcal",
    nutrient: "Nutrient",
    thisWeek: "This week",
    target: "Target",
    day: "Day",
    date: "Date",
    meal: "Meal",
    whyHere: "Why it is here",
    rows: "Rows",
    focusIron: "Iron",
    focusCalcium: "Calcium",
    focusProtein: "Protein",
    focusFiber: "Fiber",
    focusEnergy: "Energy",
    compareKicker: "With BabyBite · without the guesswork",
    compareTitle: "Two evenings at home",
    compareBody:
      "The picture is the story. With BabyBite: healthy meals, growth on the chart, better habits, a happy child. Without a plan: uncertain dinners, no tracking, missed changes, worry on the floor. BabyBite keeps you on the left — Indian plates, height and weight noted, guidance only.",
    otherTable: "The other child",
    thisTable: "With BabyBite",
    otherLine1: "Looks taller at the same age",
    otherLine2: "Heavier. More energy after school.",
    otherLine3: "You go home comparing",
    thisLine1: "Healthy meals on the table",
    thisLine2: "Track growth on the chart",
    thisLine3: "Better habits · happy child",
    compareNote:
      "Healthy meals today for a brighter tomorrow. Educational guidance only — we do not promise extra centimetres of height.",
    momCompareAlt:
      "Split illustration: happy mother and child with meals and a growth chart with BabyBite, versus a worried mother without a meal plan",
    artCompareScenePark: "The park",
    artCompareBridgePark: "Same class, same age — the other child looks taller.",
    artCompareSceneRelative: "The relative",
    artCompareBridgeRelative: "Questions at a visit. You come home measuring.",
    artCompareSceneWorry: "The worry",
    artCompareBridgeWorry: "BabyBite notes height and weight and writes Indian plates that feed growing.",
    growthKicker: "Height and weight",
    growthTitle: "Your child next to the usual band",
    growthBody:
      "This is the main reason mothers stay. See the usual height and weight for this age. The meals feed energy, protein, and calcium so the body can grow. Not a promise of extra centimetres.",
    usualHeight: "Usual height band",
    usualWeight: "Usual weight band",
    measured: "You noted",
    noExtraCm: "Not extra centimetres. Food, sleep, and play do the growing.",
    energyPlate: "Energy on the plate",
    proteinPlate: "Protein on the plate",
    calciumPlate: "Calcium on the plate",
    artTiffin: "Yellow tiffin with rice, dal, and vegetables",
    artHeroDinner: "Mother thinking about what to prepare for dinner tonight",
    artBondMotherChild: "Mother and baby sitting together at the table",
    artTiffins: "Five Indian tiffin plates for the week",
    artNutrients: "Protein, iron, calcium, and energy on one plate",
    artFeeding: "Mother feeding her child at the table",
    artMark: "A child, a book, and tonight’s plate",
    artCompare: "A tired child at the table, then a child with energy from food, sleep, and play",
    showcaseKicker: "Tonight at this table",
    whyTonight: "Why this dinner",
    otherKids: "Other kids tonight",
    yourKitchen: "This kitchen this month",
    lightMode: "Light",
    darkMode: "Dark",
    tryAgain: "Try again",
    goHome: "Home",
    myPlan: "My plan",
    pageMissing: "That page isn’t on the table.",
    holdOn: "Hold on",
    dinnerThatWay: "Head back. Dinner is still this way.",
    oauthFail: "Google sign-in could not finish. Check your connection and try again.",
    badLogin: "Invalid email or password",
    acceptTerms: "Please accept the Terms & Conditions to continue",
    signupFail: "Could not create the account",
    emailTaken: "This email already has an account. Sign in instead.",
    createdSignIn: "Account created. Please sign in.",
    welcomeBite: "Welcome to BabyBite",
    couldNotLoad: "Could not load this page",
    finishStep: "Finish this step to open tonight’s meals.",
    signInFirst: "Sign in and complete onboarding first",
    analysisNote: "The plates follow what you told us. Thirty days and a fridge PDF come after this step.",
    fridgeNext: "Fridge PDF next",
    payCalendar: "Thirty days of Indian meals, rotated so the table does not repeat itself",
    payRhythm: "Breakfast, two snacks, lunch, and dinner — portions for ages 4–12",
    payFridge: "The print copy, built from the onboarding you just finished",
    payNotes: "Protein, iron, calcium, and fibre explained in kitchen language",
    payGrowth: "Height and weight band for your child's age, then plates that feed growing",
    eduOnly: "Educational guidance only — not medical advice.",
    writingPlate: "Writing tonight’s plate…",
    lostTitle: "Lost",
    settingsTitle: "Child & kitchen",
    appearance: "Appearance",
    appearanceHint: "Light or dark",
    profileSaved: "Profile saved",
    saveProfile: "Save profile",
    planRebuilt: "Meal plan rebuilt",
    rebuildPlan: "Rebuild meal plan",
    rebuilding: "Rebuilding…",
    account: "Account",
    goalHealthyHint: "Balanced Indian meals, age portions, five slots a day.",
    goalHabitsHint: "A calmer table rhythm. Snacks and dinner at a known time.",
    goalProteinHint: "Dal, paneer, eggs, sprouts — protein in the kitchen you already have.",
    goalBalanceHint: "Rice, dal, vegetable, and fat in one plate, not an adult thali.",
    goalVarietyHint: "New grains and vegetables, rotated so picky eaters see them again.",
    failedPlan: "Could not load the meal plan",
    failedAnalysis: "Could not load the table reading",
    failedSettings: "Could not load settings",
    calendar: "Calendar",
    rhythm: "Rhythm",
    notes: "Notes",
    invalidEmail: "Enter a valid email",
    downloadPdf: "Download PDF",
    sendPdfEmail: "Send details on mail",
    resendPdfEmail: "Resend the mail",
    downloading: "Downloading…",
    sendingEmail: "Sending…",
    pdfSent: "PDF sent to your email",
    pdfDownloadFail: "Could not download the PDF",
    pdfSendFail: "Could not send the PDF by email",
    genericApiError: "Something went wrong. Please try again.",
    allergyNoPrefix: "No",
    avoidFood: "Avoid",
    logOut: "Log out",
    loggingOut: "Signing out…",
    setChild: "Child",
    setKitchen: "Kitchen",
    setFocus: "Focus",
    setPlan: "Meal pack",
    setPlanNote: "Download the fridge PDF, or rewrite the 30 days from this kitchen.",
    signedInAs: "Signed in",
    setLede: "Change the child or the kitchen. Save when you are done.",
    pickOne: "Pick one",
    unsavedHint: "Not saved yet",
    unsavedLeave: "Your changes are not saved. Log out anyway?",
    saveChanges: "Save changes",
    savedNeedRebuild: "Saved. Rewrite the 30 days so dinner matches this kitchen.",
    payKicker: "Unlock the 30 days",
    payTitle: "Tonight, written",
    payOff: "80% off",
    payJust: "₹159 for 30 days and the fridge PDF",
    payMethod: "Pay with",
    payCard: "Card",
    payUpi: "UPI",
    payNowBtn: "Pay ₹159",
    paying: "Confirming…",
    processing: "Processing...",
    done: "Done",
    paySecure: "Thirty days and the fridge PDF after this step.",
    cardNumber: "Card number",
    cardExpiry: "Expiry",
    cardCvv: "CVV",
    cardHint: "Enter the card details to continue",
    upiId: "UPI ID",
    upiHint: "Enter a UPI ID to continue",
    successKicker: "It's written",
    successTitle: "The growing years",
    successPeak: "Peak growing years",
    successLead: "Height climbs fastest in these school years.",
    successBody:
      "The fridge PDF follows energy, protein, and calcium so the body can do its own growing. Educational guidance only — not extra centimetres promised.",
    successWriting: "Writing the 30 days…",
    trustLine: "Written for ages 4–12. Educational only. Ask your paediatrician for growth concerns.",
    firstNoted: "First note",
    nowNoted: "Now",
    remeasureHint: "Note again after 30 days. Compare first, now, and the usual band. This does not promise extra centimetres.",
    addChild: "Add another child",
    switchChild: "Whose kitchen?",
  },
  ta: {
    makePlan: "என் குழந்தைக்கு உணவுத் திட்டம்",
    haveAccount: "எனக்கு கணக்கு உள்ளது",
    seeHow: "எப்படி இருக்கும் என்று பார்",
    tonight: "இன்று இரவு",
    forYou: "உங்களுக்கு",
    also: "இன்னும்",
    later: "பிறகு",
    you: "நீங்கள்",
    signIn: "உள்நுழை",
    childKitchen: "குழந்தை & சமையல்",
    showThirty: "30 நாள் திட்டத்தைக் காட்டு",
    openTonight: "இன்றிரவு உணவைத் திற",
    continueChild: "குழந்தை விவரங்களைத் தொடர்",
    fridgePdf: "ஃபிரிட்ஜ் PDF பெறு",
    whatsapp: "WhatsApp-ல் அனுப்பு",
    grocery: "இன்று வீட்டில் வைத்திருங்கள்",
    dinnerIs: "இரவு உணவு",
    breakfast: "காலை உணவு",
    lunch: "மதிய உணவு",
    snack: "சிற்றுண்டி",
    sampleCaption: "4–12 வயது குழந்தைகளுக்கான இந்திய உணவு",
    sampleFor: "7 வயது. தென் இந்திய சமையல்.",
    writingDinner: "இன்றிரவு தட்டு எழுதப்படுகிறது…",
    planReady: "இன்றிரவு தயார்",
    table: "பட்டியல்",
    why: "ஏன்",
    whatsDinner: "இன்றிரவு என்ன?",
    ourPlates: "தட்டுகள்",
    howTitle: "இரவு உணவு எப்படி முடிவு ஆகும்",
    step1: "எப்படி சமைக்கிறீர்கள் என்று சொல்லுங்கள்",
    step1Body: "4–12 வயது, சமையல், ஒவ்வாமை. ஐந்து நிமிடம். பிறகு உங்கள் வீட்டு உணவிலேயே.",
    step2: "இன்றிரவு எழுதப்பட்டுவிட்டது",
    step2Body: "காலை முதல் இரவு வரை. மேசை மீண்டும் மீண்டும் ஆகாது.",
    step3: "ஃபிரிட்ஜ் PDF ஒட்டுங்கள்",
    step3Body: "30 நாள் காகிதத்தில். இன்றிரவை WhatsApp-ல். 7 மணி கேள்வி இல்லை.",
    noSeven: "மாலை 7 கேள்வி இல்லை",
    bandBody: "30 நாள் இந்திய உணவு. ஃபிரிட்ஜ் PDF. இன்றிரவை WhatsApp-ல்.",
    footerTag: "4–12 வயது குழந்தைகளின் தாய்மார்களுக்கு",
    duoKicker: "சமையலறையில் இருந்து",
    duoTitle: "காலை, பிறகு மதியம்",
    bondKicker: "அம்மாவும் குழந்தையும்",
    bondTitle: "இரவு உணவுதான் அணைப்பு",
    bondBody:
      "பள்ளிக்குப் பிறகு கேள்வி ஒன்றுதான். BabyBite தட்டை எழுதும். நீங்கள் உட்கார்ந்து, அவர்களைப் பார்த்து, சேர்ந்து சாப்பிடுங்கள்.",
    bondTag: "சேர்ந்து சாப்பிடுவோம்",
    menuTag: "4–12 வயது குழந்தைகளுக்கான இந்திய உணவு.",
    stickerTonight: "இன்று இரவு",
    stickerAges: "4–12 வயது",
    stickerKitchen: "இந்திய சமையல்",
    stickerFridge: "ஃபிரிட்ஜ் PDF",
    stickerSimple: "எளிதாக வையுங்கள்",
    stickerProtein: "புரதம்",
    stickerPicky: "சாப்பாடு பிடிக்காதா?",
    stickerSchool: "பள்ளி மதிய உணவு",
    stickerSeven: "மாலை 7 முடிந்தது",
    stickerGrains: "ராகி · பருப்பு · தயிர்",
    stickerRegion: "தெற்கு · வடக்கு · கலவை",
    stickerDinnerQ: "இன்றிரவு என்ன?",
    benefitKicker: "அம்மாக்கள் ஏன் இருக்கிறார்கள்",
    benefitTitle: "மேசை உதவி — யூகிக்க ஒரு பட்டி அல்ல",
    benefitThirty: "30 நாளும் எழுதப்பட்டுள்ளது",
    benefitChecklist: "உங்கள் சமையல் பதில்களிலிருந்து",
    benefitNoGuess: "மாலை 7க்கு யூகம் இல்லை",
    benefitTiffin: "பயணிக்கும் பள்ளி பெட்டி",
    benefitPdf: "ஃபிரிட்ஜில் PDF",
    benefitPicky: "கவனமான சாப்பாட்டுக்கு உதவி",
    benefitProtein: "சண்டையின்றி புரதம்",
    benefitAges: "4–12 வயதுக்கு",
    welcomeBack: "மீண்டும் வருக",
    createAccount: "கணக்கை உருவாக்குங்கள்",
    authNote: "4–12 வயது குழந்தைகளுக்கான இந்திய தட்டு.",
    fullName: "முழுப் பெயர்",
    email: "மின்னஞ்சல்",
    password: "கடவுச்சொல்",
    confirmPassword: "கடவுச்சொல்லை உறுதிப்படுத்து",
    passwordHint: "8+ எழுத்துகள், எழுத்தும் எண்ணும்",
    createAccountBtn: "கணக்கை உருவாக்கு",
    creating: "உருவாக்குகிறது…",
    signingIn: "உள்நுழைகிறது…",
    or: "அல்லது",
    continueGoogle: "Google-ல் தொடரவும்",
    reviewTerms: "விதிமுறைகளை மீண்டும் பார்",
    haveAccountQ: "கணக்கு உள்ளதா?",
    noAccount: "கணக்கு இல்லையா?",
    createOne: "ஒன்றை உருவாக்கு",
    acceptedTermsNote:
      "விதிமுறைகளை ஏற்றுக்கொண்டீர்கள் (கல்வி மட்டும் — மருத்துவ முடிவுக்கு மருத்துவரை அணுகுங்கள்).",
    termsTitle: "விதிமுறைகள்",
    termsSub: "4–12 வயது குழந்தைகளின் தாய்மார்களுக்கு",
    termsRequired: "பதிவுக்கு முன் தேவை",
    termsScroll: "தொடர கீழே நகர்த்துங்கள்",
    termsDecline: "மறு",
    termsAgree: "ஏற்கிறேன் — கணக்கு உருவாக்கு",
    termsVersion: "பதிப்பு",
    closeMenu: "மெனுவை மூடு",
    openMenu: "மெனுவை திற",
    language: "மொழி",
    obTitle1: "மற்ற குழந்தைகளுக்கு அடுத்தவர்",
    obTitle2: "வீட்டில் எப்படி சமைக்கிறீர்கள்",
    obTitleKitchen: "இன்றிரவு சமையலறையில் உண்மை",
    obTitle3: "மேசையில் எது கடினம்",
    obTitle4: "இந்த மாதம் என்ன வேண்டும்",
    obTitle5: "இதிலிருந்து எழுதுவோம்",
    obLede1: "பெயர், வயது, பிறகு உயரம் மற்றும் எடை. அந்த ஒப்பீடுதான் பெரும்பாலான தாய்மார்களை இங்கே கொண்டுவரும். 4–12 வயது வழக்கமான வரம்பைக் காட்டுவோம். தட்டு வளர்ச்சிக்கு உணவளிக்கும் — கூடுதல் சென்டிமீட்டர் வாக்குறுதி இல்லை.",
    obLede2: "சைவம், முட்டை, அல்லது அசைவம். தெற்கு, வடக்கு, அல்லது கலவை. உங்கள் சமையலே.",
    obLedeKitchen: "பத்து நிமிடமா அல்லது முழு சமையலா. பணம் இறுக்கமா. சோறா இல்லையா. பள்ளி டிப்பினா வீட்டு சாப்பாடா.",
    obLede3: "சாப்பாடு பிடிக்காதது, காய்கறி தவிர்ப்பது, சோர்வு: இந்த மாதம் உண்மையானதைத் தேர்வு.",
    obLede4: "அடுத்த 30 நாளுக்கு ஒரே கவனம். PDF-ம் உணவும் இதைப் பின்பற்றும்.",
    obLede5: "படத்தைப் பாருங்கள். அடுத்து பட்டியல் — பிறகு இன்றிரவு தட்டும் ஃபிரிட்ஜ் PDF-ம்.",
    roomChild: "குழந்தை",
    roomFood: "உணவு",
    roomKitchen: "இன்றிரவு",
    roomChallenges: "சிக்கல்கள்",
    roomGoal: "இலக்கு",
    roomReview: "சரிபார்",
    cookTime: "இன்றிரவு எவ்வளவு நேரம்",
    cookTenMin: "10 நிமிடம்",
    cookNormal: "சமைக்கலாம்",
    cookTenMinHint: "கேட்கும் முன் தயாராகும் சிற்றுண்டி மற்றும் தட்டு.",
    cookNormalHint: "வழக்கமான இந்திய சமைப்பு — தோசை, பருப்பு, சப்ஜி.",
    kitchenMoney: "கிரானரி பெட்டி",
    budgetTight: "மலிவாக வை",
    budgetNormal: "வழக்கம்",
    budgetTightHint: "பருப்பு, கடலை, வாழை, ரொட்டி. வீட்டில் உள்ளது.",
    budgetNormalHint: "சில நாட்கள் பனீர் அல்லது மீன் இருக்கலாம்.",
    kitchenRice: "மேசையில் சோறு",
    riceEats: "சோறு சாப்பிடுவார்",
    riceRefuses: "இன்றிரவு சோறு வேண்டாம்",
    riceEatsHint: "சாம்பார் சாதம், புலாவ், பருப்பு சாதம் இருக்கலாம்.",
    riceRefusesHint: "ரொட்டி, தோசை, பொஹா, சிறுதானியம் — தட்டு சோறுக்கு பதில்.",
    kitchenTiffin: "பள்ளி டிப்பின்",
    tiffinSchool: "பள்ளி டிப்பின்",
    tiffinHome: "வீட்டில் மட்டும்",
    tiffinSchoolHint: "பயணம் செய்யும் பெட்டி — ரேப், பராத்தா, இட்லி, பொஹா.",
    tiffinHomeHint: "மதியம் வீட்டு மேசையில்.",
    roomByMeal: "நேரப்படி",
    roomByProblem: "சிக்கல்படி",
    roomBrowseKicker: "ஒவ்வொன்றும் கீழே யோசனைகளைத் திறக்கும்",
    roomHasMoreLists: "கீழே பட்டியல் விருப்பங்கள் திறக்கும்",
    roomPlanLabel: "நாள்காட்டி",
    roomBrowseLabel: "சமையலறை பட்டியல்கள்",
    roomBrowseMealHint: "காலை, மதியம், இரவு & சிற்றுண்டி",
    roomBrowseProblemHint: "நேரம், செலவு, டிப்பின் & தேர்வு",
    roomCaptionToday: "இன்றைய ஐந்து உணவுகள்",
    roomCaptionWeek: "வாரம் முழுவதும்",
    roomCaptionMonth: "30 நாள் — நாளைத் தட்டவும்",
    roomCaptionTiffin: "வார நாள் பள்ளி டிப்பின்",
    roomCaptionMeals: "உணவு நேரப்படி யோசனைகள்",
    roomCaptionProblems: "உங்கள் தேவைப்படி யோசனைகள்",
    roomTiffin: "டிப்பின் வாரம்",
    plateAges45: "4–5 வயது தட்டு",
    plateAges68: "6–8 வயது தட்டு",
    plateAges912: "9–12 வயது தட்டு",
    sameLunchNote: "அதே மதிய உணவு திரும்ப வருகிறது — பெட்டி மாற்று இங்கே.",
    tiffinWeekHint: "வார நாள் பள்ளி டிப்பின். மறுத்தால் மாற்று.",
    schoolFilter: "பெட்டி மதிய உணவு மாற்றம்",
    boxLunchSwapTitle: "பெட்டி மதிய உணவு மாற்றம்",
    boxLunchSwapLead: "இந்த நாளுக்கு பெட்டியில் அனுப்பும் மதிய உணவை மாற்றுங்கள்.",
    todaysPackableLunch: "இன்றைய பெட்டி மதிய உணவு",
    packableLunch: "பெட்டி மதிய உணவு",
    packableBadge: "பள்ளி பெட்டி · எடுத்துச் செல்லலாம்",
    swapWithLabel: "இதற்கு பதிலாக",
    selectMeal: "தேர்ந்தெடு",
    selectedMeal: "தேர்ந்தெடுக்கப்பட்டது",
    viewMealDetails: "உணவைப் பார்",
    confirmLunchSwap: "மதிய உணவு மாற்றத்தை உறுதி செய்",
    lunchSwapUpdated: "பெட்டி மதிய உணவு புதுப்பிக்கப்பட்டது!",
    lunchSwapFailed: "மதிய உணவை மாற்ற முடியவில்லை. மீண்டும் முயற்சிக்கவும்.",
    schoolFilterHint: "இன்று & வாரம் — பள்ளிக்கு எடுத்துச் செல்லும் பெட்டி மதிய உணவு.",
    checklistBuilt: "உங்கள் பட்டியலில் இருந்து",
    funnelRerouteHint: "ஒரு படி தவறிவிட்டீர்கள் — உங்கள் இடம் சேமிக்கப்பட்டது. இங்கே தொடருங்கள்:",
    whyThisPlate: "இந்தத் தட்டு ஏன்",
    schoolFilterEmpty: "இந்த சமையலறையில் பெட்டி மதிய உணவு இல்லை. வேறு பட்டியலை முயற்சிக்கவும்.",
    listBreakfast: "காலை",
    listLunch: "மதியம்",
    listDinner: "இரவு",
    listSnacks: "சிற்றுண்டி",
    listTenMin: "10 நிமிட உணவு",
    listBudget: "மலிவு உணவு",
    listSchool: "பள்ளி டிப்பின்",
    listFavourite: "குழந்தைக்கு பிடித்தது",
    listNoRice: "சோறு இல்லை",
    listHomemade: "வீட்டு சிற்றுண்டி",
    kitchenPickMeal: "எந்த உணவுப் பட்டியல்?",
    kitchenPickProblem: "இன்று என்ன உதவி வேண்டும்?",
    kitchenIdeasCount: "பட்டியலில் உள்ள யோசனைகள்",
    kitchenListCount: "பட்டியல்கள்",
    hintListBreakfast: "பள்ளிக்கு முன் காலை தட்டு",
    hintListLunch: "வீட்டில் அல்லது பெட்டி மதிய உணவு",
    hintListDinner: "முழு குடும்பத்துக்கு இரவு",
    hintListSnacks: "உணவுக்கு இடையில் சிற்றுண்டி",
    hintListTenMin: "நேரம் குறைவாக இருக்கும்போது",
    hintListBudget: "வார செலவுக்கு மென்மை",
    hintListSchool: "பெட்டிக்கு ஏற்ற மதிய உணவு",
    hintListFavourite: "தேர்வு குழந்தை & பிடித்தவை",
    hintListNoRice: "சோறு இல்லாத தட்டுகள்",
    hintListHomemade: "வீட்டில், பாக்கெட்டிலிருந்து அல்ல",
    ifTheyRefuse: "இதை மறுத்தால்",
    minutesWord: "நிமிடம்",
    pantryLine: "பெட்டியில் இருந்து",
    familyPotNote: "அதே பானை, குழந்தைக்கு மென்மை.",
    kitchenLine: "விரைவு மாலை சிற்றுண்டி, சோறுக்கு மாற்று, வீட்டில் உள்ளதில் 10 நிமிட உணவு.",
    emptyKitchenList: "இந்த சமையலறைக்கு இந்த பட்டியல் காலியாக உள்ளது. வேறு சிக்கலைப் பாருங்கள்.",
    snacksThisWeek: "இந்த வார சிற்றுண்டி",
    stepOf: "படி",
    of: "/",
    field: "புலம்",
    yourAnswer: "உங்கள் பதில்",
    name: "பெயர்",
    age: "வயது",
    gender: "பாலினம்",
    boy: "ஆண்",
    girl: "பெண்",
    other: "மற்றவை",
    ageRange: "4–12 வயது மட்டும்",
    genderHint: "ஆண் அல்லது பெண்",
    optionalHw: "உயரம் & எடை — ஒப்பீடு",
    hwMain: "பூங்கா ஒப்பீடு",
    hwLede: "அதே வயது மற்ற குழந்தைகள் உயரமாகவோ கனமாகவோ தெரியலாம். உங்கள் குழந்தையின் உயரம், எடையை எழுதுங்கள். வழக்கமான வரம்பைப் பாருங்கள். பிறகு ஆற்றல், புரதம், கால்சியத்துக்கு தட்டு எழுதுவோம்.",
    hwBand: "இந்த வயதுக்கு வழக்கம்",
    hwSkip: "இன்று அளவுகோல் இல்லையா? காலியாக விட்டு பின்னர் சேர்க்கலாம்.",
    heightCm: "உயரம் செ.மீ",
    weightKg: "எடை கி.கி",
    anyAllergies: "ஒவ்வாமை உள்ளதா? (விருப்பம்)",
    foodsAvoid: "தவிர்க்க வேண்டிய உணவு (விருப்பம்)",
    foodsAvoidPh: "எ.கா. காளான், பாகற்காய்",
    namePh: "எ.கா. ஆன்யா, ரோகன்…",
    choice: "தேர்வு",
    now: "இப்போது",
    diet: "உணவு முறை",
    style: "பாணி",
    dietHome: "வீட்டு உணவு",
    regionStyle: "பிராந்திய பாணி",
    veg: "சைவம்",
    egg: "முட்டை சைவம்",
    nonveg: "அசைவம்",
    south: "தென் இந்திய",
    north: "வட இந்திய",
    mixed: "கலவை",
    vegHint: "தாவர உணவு",
    eggHint: "முட்டை உண்டு",
    nonvegHint: "இறைச்சி உண்டு",
    southHint: "தோசை, சாம்பார், சோறு",
    northHint: "ரோட்டி, பராத்தா, பருப்பு",
    mixedHint: "இரண்டும்",
    challengeTick: "இந்த மாதம் மேசையில் உண்மையானதை எல்லாம் தேர்வு. ஒன்றுக்கு மேல் சரி.",
    pickyHint: "புதிய உணவை மறுக்கும்",
    underHint: "அதிக கலோரி தேவை",
    vegSkipHint: "காய்கறி தவிர்க்கும்",
    readyFor: "தயார்",
    seeTable: "பட்டியலைப் பார்",
    continue: "தொடர்",
    back: "பின்",
    saving: "சேமிக்கிறது…",
    yourChild: "உங்கள் குழந்தை",
    years: "வயது",
    enterName: "குழந்தையின் பெயரை உள்ளிடுங்கள்",
    pickChallenge: "ஒரு சிக்கலாவது தேர்வு",
    selectChallenge: "ஒரு சிக்கலாவது தேர்வு",
    signInToSave: "சுயவிவரத்தைச் சேமிக்க உள்நுழையுங்கள்",
    nextReadTable: "அடுத்து உங்கள் குழந்தையை வழக்கமான உயரம்–எடை வரம்புக்கு அருகில் வைப்போம். பிறகு இன்றிரவு தட்டும் ஃபிரிட்ஜ் PDF-ம்.",
    allergyDairy: "பால்",
    allergyNuts: "கொட்டைகள்",
    allergyEggs: "முட்டை",
    allergyGluten: "கோதுமை / குளுட்டன்",
    allergySoy: "சோயா",
    allergySeafood: "மீன் / கடல் உணவு",
    chUnder: "எடை குறைவு",
    chAppetite: "பசி குறைவு",
    chPicky: "சாப்பாடு பிடிக்காது",
    chVeg: "காய்கறி பிடிக்காது",
    chMilk: "பால் குடிக்காது",
    chEnergy: "சோர்வு",
    chSports: "விளையாட்டு குழந்தை",
    goalHealthy: "ஆரோக்கிய ஊட்டம்",
    goalHabits: "நல்ல உணவு பழக்கம்",
    goalProtein: "புரத கவனம்",
    goalBalance: "சமநிலை உணவு",
    goalVariety: "உணவு வகை அதிகம்",
    roomToday: "இன்று",
    roomWeek: "இந்த வாரம்",
    roomMonth: "30 நாள்",
    monthHint: "ஒரு நாளுக்கு ஒரு மதிய உணவு. ஐந்து தட்டுகளுக்கும் ஒரு நாளைத் தட்டவும்.",
    roomGoals: "இலக்கு",
    morningSnack: "காலை சிற்றுண்டி",
    eveningSnack: "மாலை சிற்றுண்டி",
    kcal: "கலோரி",
    nutrient: "ஊட்டம்",
    thisWeek: "இந்த வாரம்",
    target: "இலக்கு",
    day: "நாள்",
    date: "தேதி",
    meal: "உணவு",
    whyHere: "ஏன் இங்கே",
    rows: "வரிசை",
    focusIron: "இரும்பு",
    focusCalcium: "கால்சியம்",
    focusProtein: "புரதம்",
    focusFiber: "நார்",
    focusEnergy: "ஆற்றல்",
    compareKicker: "BabyBite உடன் · யூகம் இல்லாமல்",
    compareTitle: "வீட்டில் இரண்டு மாலைகள்",
    compareBody:
      "படம் கதையைச் சொல்கிறது. BabyBite உடன்: ஆரோக்கிய உணவு, வளர்ச்சி வரைபடம், நல்ல பழக்கம், மகிழ்ச்சியான குழந்தை. திட்டம் இல்லாமல்: உணவு குழப்பம், கண்காணிப்பு இல்லை, தவறவிட்ட மாற்றங்கள், தரையில் கவலை. BabyBite இடது பக்கத்தில் — இந்திய தட்டு, உயரம் எடை குறிப்பு, கல்வி வழிகாட்டுதல் மட்டும்.",
    otherTable: "மற்ற குழந்தை",
    thisTable: "BabyBite உடன்",
    otherLine1: "அதே வயதில் உயரமாகத் தெரியும்",
    otherLine2: "கனம் அதிகம். பள்ளிக்குப் பின் ஆற்றல் அதிகம்.",
    otherLine3: "வீட்டுக்கு வந்து ஒப்பிடுகிறீர்கள்",
    thisLine1: "மேசையில் ஆரோக்கிய உணவு",
    thisLine2: "வரைபடத்தில் வளர்ச்சி கண்காணிப்பு",
    thisLine3: "நல்ல பழக்கம் · மகிழ்ச்சியான குழந்தை",
    compareNote:
      "இன்று ஆரோக்கிய உணவு — நாளை பிரகாசமான நாள். கல்வி வழிகாட்டுதல் மட்டும் — கூடுதல் சென்டிமீட்டர் வாக்குறுதி இல்லை.",
    momCompareAlt:
      "பிளவு வரைபடம்: BabyBite உடன் உணவும் வளர்ச்சி வரைபடமும் உள்ள மகிழ்ச்சியான அம்மா–குழந்தை; திட்டம் இல்லாமல் கவலையான அம்மா",
    artCompareScenePark: "பூங்கா",
    artCompareBridgePark: "அதே வகுப்பு, அதே வயது — மற்ற குழந்தை உயரமாகத் தெரிகிறது.",
    artCompareSceneRelative: "உறவினர்",
    artCompareBridgeRelative: "சந்திப்பில் கேள்விகள். வீட்டுக்கு வந்து அளவிவிடுகிறீர்கள்.",
    artCompareSceneWorry: "கவலை",
    artCompareBridgeWorry: "BabyBite உயரம், எடை குறித்து இந்திய தட்டுகள் எழுதும்.",
    growthKicker: "உயரம் மற்றும் எடை",
    growthTitle: "வழக்கமான வரம்புக்கு அடுத்தவர்",
    growthBody:
      "தாய்மார்கள் இங்கே இருப்பதற்கான முக்கிய காரணம் இது. இந்த வயது வழக்கமான உயரம், எடையைப் பாருங்கள். உணவு ஆற்றல், புரதம், கால்சியம் கொடுக்கும். கூடுதல் சென்டிமீட்டர் வாக்குறுதி இல்லை.",
    usualHeight: "வழக்கமான உயரம்",
    usualWeight: "வழக்கமான எடை",
    measured: "நீங்கள் குறித்தது",
    noExtraCm: "கூடுதல் சென்டிமீட்டர் இல்லை. உணவு, தூக்கம், விளையாட்டு வளர்க்கும்.",
    energyPlate: "தட்டில் ஆற்றல்",
    proteinPlate: "தட்டில் புரதம்",
    calciumPlate: "தட்டில் கால்சியம்",
    artTiffin: "சாதம், பருப்பு, காய்கறி உள்ள மஞ்சள் டிப்பின்",
    artHeroDinner: "இன்றிரவு என்ன சமைப்பது என்று யோசிக்கும் அம்மா",
    artBondMotherChild: "அம்மாவும் குழந்தையும் மேசையில் சேர்ந்து அமர்ந்துள்ளனர்",
    artTiffins: "வாரத்துக்கு ஐந்து இந்திய டிப்பின் தட்டுகள்",
    artNutrients: "ஒரு தட்டில் புரதம், இரும்பு, கால்சியம், ஆற்றல்",
    artFeeding: "மேசையில் குழந்தைக்கு உணவூட்டும் அம்மா",
    artMark: "குழந்தை, புத்தகம், இன்றிரவு தட்டு",
    artCompare: "மேசையில் சோர்வான குழந்தை, பிறகு உணவு, தூக்கம், விளையாட்டால் ஆற்றல் பெற்ற குழந்தை",
    showcaseKicker: "இன்றிரவு இந்த மேசையில்",
    whyTonight: "இந்த இரவு ஏன்",
    otherKids: "மற்ற குழந்தைகள் இன்றிரவு",
    yourKitchen: "இந்த மாதம் இந்த சமையலறை",
    lightMode: "வெளிச்சம்",
    darkMode: "இருள்",
    tryAgain: "மீண்டும் முயலவும்",
    goHome: "முகப்பு",
    myPlan: "என் திட்டம்",
    pageMissing: "அந்த பக்கம் மேசையில் இல்லை.",
    holdOn: "சற்று பொறுங்கள்",
    dinnerThatWay: "திரும்பி வாருங்கள். இரவு உணவு இந்த வழியில்தான்.",
    oauthFail: "Google உள்நுழைவு முடியவில்லை. இணைப்பைப் பார்த்து மீண்டும் முயலவும்.",
    badLogin: "மின்னஞ்சல் அல்லது கடவுச்சொல் தவறு",
    acceptTerms: "தொடர விதிமுறைகளை ஏற்கவும்",
    signupFail: "கணக்கு உருவாக்க முடியவில்லை",
    emailTaken: "இந்த மின்னஞ்சலுக்கு கணக்கு உள்ளது. உள்நுழையவும்.",
    createdSignIn: "கணக்கு உருவானது. உள்நுழையவும்.",
    welcomeBite: "BabyBite-க்கு வரவேற்கிறோம்",
    couldNotLoad: "இந்த பக்கத்தை ஏற்ற முடியவில்லை",
    finishStep: "இன்றிரவு உணவைத் திறக்க இந்த படியை முடிக்கவும்.",
    signInFirst: "முதலில் உள்நுழைந்து ஆன்போர்டிங் முடிக்கவும்",
    analysisNote: "நீங்கள் சொன்னதையே தட்டுகள் பின்பற்றும். 30 நாள் மற்றும் ஃபிரிட்ஜ் PDF அடுத்த படி.",
    fridgeNext: "அடுத்து ஃபிரிட்ஜ் PDF",
    payCalendar: "30 நாள் இந்திய உணவு, மேசை மீளாமல் சுழலும்",
    payRhythm: "காலை உணவு, இரண்டு சிற்றுண்டி, மதியம், இரவு — 4–12 பங்கு",
    payFridge: "நீங்கள் முடித்த ஆன்போர்டிங்கிலிருந்து அச்சிடும் நகல்",
    payNotes: "புரதம், இரும்பு, கால்சியம், நார் — சமையலறை மொழியில்",
    payGrowth: "உங்கள் குழந்தையின் வயது உயரம்–எடை வரம்பு, பிறகு வளர்ச்சிக்கு தட்டு",
    eduOnly: "கல்வி வழிகாட்டுதல் மட்டும் — மருத்துவ ஆலோசனை அல்ல.",
    writingPlate: "இன்றிரவு தட்டை எழுதுகிறோம்…",
    lostTitle: "காணவில்லை",
    settingsTitle: "குழந்தை மற்றும் சமையலறை",
    appearance: "தோற்றம்",
    appearanceHint: "வெளிச்சம் அல்லது இருள்",
    profileSaved: "சுயவிவரம் சேமிக்கப்பட்டது",
    saveProfile: "சுயவிவரம் சேமி",
    planRebuilt: "உணவுத் திட்டம் மீண்டும் எழுதப்பட்டது",
    rebuildPlan: "திட்டத்தை மீண்டும் எழுது",
    rebuilding: "மீண்டும் எழுதுகிறோம்…",
    account: "கணக்கு",
    goalHealthyHint: "சமநிலை இந்திய உணவு, வயது பங்கு, நாளைக்கு ஐந்து நேரம்.",
    goalHabitsHint: "அமைதியான மேசை நேரம். சிற்றுண்டி மற்றும் இரவு தெரிந்த நேரத்தில்.",
    goalProteinHint: "பருப்பு, பனீர், முட்டை, முளை — உங்கள் சமையலறையிலேயே புரதம்.",
    goalBalanceHint: "சோறு, பருப்பு, காய்கறி, கொழுப்பு ஒரே தட்டில் — பெரியவர் தட்டு அல்ல.",
    goalVarietyHint: "புதிய தானியம், காய்கறி — பிடிக்காத குழந்தை மீண்டும் பார்க்கும்.",
    failedPlan: "உணவுத் திட்டத்தை ஏற்ற முடியவில்லை",
    failedAnalysis: "மேசை வாசிப்பை ஏற்ற முடியவில்லை",
    failedSettings: "அமைப்புகளை ஏற்ற முடியவில்லை",
    calendar: "நாட்காட்டி",
    rhythm: "தாளம்",
    notes: "குறிப்பு",
    invalidEmail: "சரியான மின்னஞ்சல் எழுதவும்",
    downloadPdf: "PDF பதிவிறக்கு",
    sendPdfEmail: "விவரங்களை மின்னஞ்சலில் அனுப்பு",
    resendPdfEmail: "மின்னஞ்சலை மீண்டும் அனுப்பு",
    downloading: "பதிவிறக்குகிறோம்…",
    sendingEmail: "அனுப்புகிறோம்…",
    pdfSent: "PDF உங்கள் மின்னஞ்சலுக்கு அனுப்பப்பட்டது",
    pdfDownloadFail: "PDF பதிவிறக்க முடியவில்லை",
    pdfSendFail: "மின்னஞ்சலில் PDF அனுப்ப முடியவில்லை",
    genericApiError: "ஏதோ தவறு. மீண்டும் முயற்சிக்கவும்.",
    allergyNoPrefix: "இல்லை",
    avoidFood: "தவிர்",
    logOut: "வெளியேறு",
    loggingOut: "வெளியேறுகிறோம்…",
    setChild: "குழந்தை",
    setKitchen: "சமையலறை",
    setFocus: "கவனம்",
    setPlan: "உணவுப் பொதி",
    setPlanNote: "ஃபிரிட்ஜ் PDF பதிவிறக்குங்கள், அல்லது இந்த சமையலறையிலிருந்து 30 நாளை மீண்டும் எழுதுங்கள்.",
    signedInAs: "உள்நுழைந்துள்ளீர்கள்",
    setLede: "குழந்தை அல்லது சமையலறையை மாற்றுங்கள். முடிந்ததும் சேமியுங்கள்.",
    pickOne: "ஒன்றைத் தேர்வு",
    unsavedHint: "இன்னும் சேமிக்கவில்லை",
    unsavedLeave: "மாற்றங்கள் சேமிக்கப்படவில்லை. இப்படியே வெளியேறவா?",
    saveChanges: "மாற்றங்களைச் சேமி",
    savedNeedRebuild: "சேமித்தோம். இந்த சமையலறைக்கு ஏற்ப 30 நாளை மீண்டும் எழுதுங்கள்.",
    payKicker: "30 நாளைத் திற",
    payTitle: "இன்றிரவு எழுதப்பட்டது",
    payOff: "80% தள்ளுபடி",
    payJust: "30 நாளும் ஃபிரிட்ஜ் PDF-ம் ₹159",
    payMethod: "செலுத்த",
    payCard: "அட்டை",
    payUpi: "UPI",
    payNowBtn: "₹159 செலுத்து",
    paying: "உறுதி செய்கிறோம்…",
    processing: "செயல்படுகிறது...",
    done: "முடிந்தது",
    paySecure: "30 நாள் உணவும் ஃபிரிட்ஜ் PDF-ம் இந்த அடியில்.",
    cardNumber: "அட்டை எண்",
    cardExpiry: "காலம்",
    cardCvv: "CVV",
    cardHint: "தொடர அட்டை விவரங்களை எழுதவும்",
    upiId: "UPI ஐடி",
    upiHint: "தொடர UPI ஐடி எழுதவும்",
    successKicker: "எழுதப்பட்டது",
    successTitle: "வளரும் ஆண்டுகள்",
    successPeak: "உயரம் வளரும் காலம்",
    successLead: "பள்ளி ஆண்டுகளில் உயரம் வேகமாக ஏறும்.",
    successBody:
      "ஃபிரிட்ஜ் PDF ஆற்றல், புரதம், கால்சியத்தைப் பின்பற்றும். உடல் தானே வளரும். கூடுதல் சென்டிமீட்டர் வாக்குறுதி இல்லை.",
    successWriting: "30 நாளை எழுதுகிறோம்…",
    trustLine: "4–12 வயதுக்கு எழுதப்பட்டது. கல்வி மட்டும். வளர்ச்சி கவலைக்கு உங்கள் குழந்தை மருத்துவரைக் கேளுங்கள்.",
    firstNoted: "முதல் குறிப்பு",
    nowNoted: "இப்போது",
    remeasureHint: "30 நாளுக்குப் பிறகு மீண்டும் எழுதுங்கள். முதல், இப்போது, வழக்கமான வரம்பை ஒப்பிடுங்கள். கூடுதல் சென்டிமீட்டர் வாக்குறுதி இல்லை.",
    addChild: "இன்னொரு குழந்தையைச் சேர்",
    switchChild: "யாருடைய சமையலறை?",
  },
  hi: {
    makePlan: "मेरे बच्चे की योजना बनाएँ",
    haveAccount: "मेरा खाता पहले से है",
    seeHow: "कैसा दिखता है, देखें",
    tonight: "आज रात",
    forYou: "आपके लिए",
    also: "और भी",
    later: "बाद में",
    you: "आप",
    signIn: "साइन इन",
    childKitchen: "बच्चा और रसोई",
    showThirty: "30 दिन की योजना दिखाएँ",
    openTonight: "आज रात की थाली खोलें",
    continueChild: "बच्चे की जानकारी जारी रखें",
    fridgePdf: "फ्रिज PDF लें",
    whatsapp: "WhatsApp पर भेजें",
    grocery: "आज घर पर रखें",
    dinnerIs: "रात का खाना",
    breakfast: "नाश्ता",
    lunch: "दोपहर का खाना",
    snack: "नाश्ता",
    sampleCaption: "4–12 साल के बच्चों के लिए भारतीय भोजन",
    sampleFor: "7 साल. दक्षिण भारतीय रसोई.",
    writingDinner: "आज रात की थाली लिखी जा रही है…",
    planReady: "आज रात तैयार है",
    table: "सूची",
    why: "क्यों",
    whatsDinner: "आज रात क्या है?",
    ourPlates: "थाली",
    howTitle: "रात का खाना कैसे तय होता है",
    step1: "बताएँ आप कैसे पकाती हैं",
    step1Body: "उम्र 4–12, रसोई, एलर्जी. पाँच मिनट. फिर आपके घर का खाना ही.",
    step2: "आज रात लिखी जा चुकी है",
    step2Body: "नाश्ते से रात तक. मेज़ दोहराती नहीं.",
    step3: "फ्रिज PDF चिपकाएँ",
    step3Body: "तीस दिन कागज पर. आज रात WhatsApp पर. शाम सात का सवाल नहीं.",
    noSeven: "शाम सात का सवाल नहीं",
    bandBody: "तीस दिन भारतीय भोजन. फ्रिज PDF. आज रात WhatsApp पर.",
    footerTag: "4–12 साल के बच्चों की माँओं के लिए",
    duoKicker: "रसोई से",
    duoTitle: "नाश्ता, फिर दोपहर",
    bondKicker: "माँ और बच्चा",
    bondTitle: "रात का खाना ही गोद है",
    bondBody:
      "स्कूल के बाद सवाल वही रहता है. BabyBite थाली लिख देता है, ताकि आप बैठें, उन्हें देखें, और साथ खाएँ.",
    bondTag: "हम साथ खाते हैं",
    menuTag: "4–12 साल के बच्चों के लिए भारतीय भोजन.",
    stickerTonight: "आज रात",
    stickerAges: "उम्र 4–12",
    stickerKitchen: "भारतीय रसोई",
    stickerFridge: "फ्रिज PDF",
    stickerSimple: "सरल रखें",
    stickerProtein: "प्रोटीन",
    stickerPicky: "खाना पसंद नहीं?",
    stickerSchool: "स्कूल लंच",
    stickerSeven: "शाम 7 तय",
    stickerGrains: "रागी · दाल · दही",
    stickerRegion: "दक्षिण · उत्तर · मिश्रित",
    stickerDinnerQ: "आज रात क्या है?",
    benefitKicker: "माएँ यहीं क्यों रहती हैं",
    benefitTitle: "मेज़ पर मदद — अनुमान लगाने का मेन्यू नहीं",
    benefitThirty: "30 दिन पहले से लिखे",
    benefitChecklist: "आपके रसोई जवाबों से",
    benefitNoGuess: "शाम 7 बजे अंदाज़ा नहीं",
    benefitTiffin: "साथ चलने वाला स्कूल डिब्बा",
    benefitPdf: "फ्रिज पर PDF",
    benefitPicky: "अकड़ खाने वालों की मदद",
    benefitProtein: "बिना लड़ाई प्रोटीन",
    benefitAges: "4–12 साल के लिए",
    welcomeBack: "वापस स्वागत है",
    createAccount: "खाता बनाएँ",
    authNote: "4–12 साल के बच्चों के लिए भारतीय थाली.",
    fullName: "पूरा नाम",
    email: "ईमेल",
    password: "पासवर्ड",
    confirmPassword: "पासवर्ड पुष्टि",
    passwordHint: "8+ अक्षर, अक्षर और अंक",
    createAccountBtn: "खाता बनाएँ",
    creating: "बन रहा है…",
    signingIn: "साइन इन हो रहा है…",
    or: "या",
    continueGoogle: "Google से जारी रखें",
    reviewTerms: "नियम फिर देखें",
    haveAccountQ: "खाता है?",
    noAccount: "खाता नहीं?",
    createOne: "एक बनाएँ",
    acceptedTermsNote:
      "आपने नियम स्वीकार किए (केवल शिक्षा — चिकित्सा निर्णय के लिए डॉक्टर से पूछें).",
    termsTitle: "नियम और शर्तें",
    termsSub: "4–12 साल के बच्चों की माँओं के लिए",
    termsRequired: "साइन अप से पहले ज़रूरी",
    termsScroll: "आगे बढ़ने के लिए नीचे स्क्रॉल करें",
    termsDecline: "अस्वीकार",
    termsAgree: "मैं सहमत हूँ — खाता बनाएँ",
    termsVersion: "संस्करण",
    closeMenu: "मेनू बंद करें",
    openMenu: "मेनू खोलें",
    language: "भाषा",
    obTitle1: "दूसरे बच्चों के पास आपका बच्चा",
    obTitle2: "घर पर कैसे पकाती हैं",
    obTitleKitchen: "आज रात रसोई में क्या सच है",
    obTitle3: "मेज़ पर क्या कठिन है",
    obTitle4: "इस महीने क्या चाहिए",
    obTitle5: "इसी से लिखेंगे",
    obLede1: "पहले नाम, उम्र, फिर कद और वज़न. यही तुलना ज़्यादातर माँओं को यहाँ लाती है. 4–12 की सामान्य पट्टी दिखाते हैं. थाली बढ़ने को खिलाती है — अतिरिक्त सेंटीमीटर का वादा नहीं.",
    obLede2: "शाकाहारी, अंडा, या मांसाहारी. दक्षिण, उत्तर, या मिश्रित. आपकी रसोई ही.",
    obLedeKitchen: "दस मिनट या पूरा पकाना. पैसे तंग या सामान्य. चावल या बिना चावल. स्कूल टिफिन या घर का खाना.",
    obLede3: "नखरे, सब्ज़ी छोड़ना, थकान: इस महीने जो सच है, चुनें.",
    obLede4: "अगले 30 दिन का एक ध्यान. PDF और खाना इसी को मानेंगे.",
    obLede5: "तस्वीर देखें. फिर सूची — फिर आज रात की थाली और फ्रिज PDF.",
    roomChild: "बच्चा",
    roomFood: "खाना",
    roomKitchen: "आज रात",
    roomChallenges: "कठिनाई",
    roomGoal: "लक्ष्य",
    roomReview: "जाँच",
    cookTime: "आज रात कितना समय",
    cookTenMin: "10 मिनट",
    cookNormal: "पका सकती हूँ",
    cookTenMinHint: "पूछने से पहले तैयार नाश्ता और थाली.",
    cookNormalHint: "सामान्य भारतीय पकान — डोसा, दाल, सब्ज़ी.",
    kitchenMoney: "किराने का डिब्बा",
    budgetTight: "सस्ता रखें",
    budgetNormal: "सामान्य",
    budgetTightHint: "दाल, चना, केला, रोटी. जो घर में है.",
    budgetNormalHint: "कुछ दिन पनीर या मछली भी चल सकती है.",
    kitchenRice: "मेज़ पर चावल",
    riceEats: "चावल खाते हैं",
    riceRefuses: "आज रात चावल नहीं",
    riceEatsHint: "सांभर चावल, पुलाव, दाल-चावल रह सकते हैं.",
    riceRefusesHint: "रोटी, डोसा, पोहा, बाजरा — थाली चावल की जगह.",
    kitchenTiffin: "स्कूल टिफिन",
    tiffinSchool: "स्कूल टिफिन",
    tiffinHome: "केवल घर",
    tiffinSchoolHint: "घूमने वाला डिब्बा — रैप, पराठा, इडली, पोहा.",
    tiffinHomeHint: "दोपहर घर की मेज़ पर.",
    roomByMeal: "समय से",
    roomByProblem: "समस्या से",
    roomBrowseKicker: "हर एक नीचे विचारों की सूची खोलता है",
    roomHasMoreLists: "नीचे सूची के विकल्प खुलते हैं",
    roomPlanLabel: "कैलेंडर",
    roomBrowseLabel: "रसोई की सूचियाँ",
    roomBrowseMealHint: "नाश्ता, दोपहर, रात & स्नैक्स",
    roomBrowseProblemHint: "समय, बजट, टिफिन & नखरे",
    roomCaptionToday: "आज के पाँच खाने",
    roomCaptionWeek: "पूरा हफ़्ता एक नज़र में",
    roomCaptionMonth: "30 दिन — दिन टैप करें",
    roomCaptionTiffin: "स्कूल के दिनों का टिफिन",
    roomCaptionMeals: "समय के हिसाब से विचार",
    roomCaptionProblems: "ज़रूरत के हिसाब से विचार",
    roomTiffin: "टिफिन सप्ताह",
    plateAges45: "4–5 साल की थाली",
    plateAges68: "6–8 साल की थाली",
    plateAges912: "9–12 साल की थाली",
    sameLunchNote: "वही दोपहर का खाना दोहराया जा रहा है — डिब्बे के विकल्प यहाँ हैं।",
    tiffinWeekHint: "सप्ताह के दिनों का स्कूल टिफिन। मना करें तो बदलें।",
    schoolFilter: "डिब्बा दोपहर बदलें",
    boxLunchSwapTitle: "डिब्बा दोपहर बदलें",
    boxLunchSwapLead: "इस दिन के लिए बच्चे का डिब्बा दोपहर का खाना बदलें।",
    todaysPackableLunch: "आज का डिब्बा दोपहर",
    packableLunch: "डिब्बा दोपहर",
    packableBadge: "स्कूल डिब्बा · साथ ले जाएँ",
    swapWithLabel: "इससे बदलें",
    selectMeal: "चुनें",
    selectedMeal: "चुना गया",
    viewMealDetails: "खाना देखें",
    confirmLunchSwap: "दोपहर बदलने की पुष्टि",
    lunchSwapUpdated: "डिब्बा दोपहर अपडेट हो गया!",
    lunchSwapFailed: "दोपहर अपडेट नहीं हो सका. फिर कोशिश करें।",
    schoolFilterHint: "आज और हफ़्ता — स्कूल डिब्बे में जाने वाला दोपहर का खाना।",
    checklistBuilt: "आपकी सूची से बना",
    funnelRerouteHint: "एक कदम छूट गया — आपकी जगह सुरक्षित है। यहाँ से आगे बढ़ें:",
    whyThisPlate: "यह थाली क्यों",
    schoolFilterEmpty: "इस रसोई में डिब्बा दोपहर नहीं मिला. दूसरी सूची आज़माएँ।",
    listBreakfast: "नाश्ता",
    listLunch: "दोपहर",
    listDinner: "रात",
    listSnacks: "स्नैक्स",
    listTenMin: "10 मिनट का खाना",
    listBudget: "सस्ता खाना",
    listSchool: "स्कूल टिफिन",
    listFavourite: "बच्चे की पसंद",
    listNoRice: "बिना चावल",
    listHomemade: "घर का नाश्ता",
    kitchenPickMeal: "कौन-सी खाने की सूची?",
    kitchenPickProblem: "आज किस चीज़ में मदद चाहिए?",
    kitchenIdeasCount: "इस सूची में विचार",
    kitchenListCount: "सूचियाँ",
    hintListBreakfast: "स्कूल से पहले सुबह की थाली",
    hintListLunch: "घर या डिब्बे का दोपहर का खाना",
    hintListDinner: "पूरे परिवार के लिए रात का खाना",
    hintListSnacks: "खाने के बीच छोटा नाश्ता",
    hintListTenMin: "जब समय कम हो",
    hintListBudget: "हफ़्ते के खर्च पर आसान",
    hintListSchool: "डिब्बे के लिए दोपहर का खाना",
    hintListFavourite: "नखरे और पसंदीदा",
    hintListNoRice: "बिना चावल की थाली",
    hintListHomemade: "घर से, पैकेट से नहीं",
    ifTheyRefuse: "अगर यह मना करें",
    minutesWord: "मिनट",
    pantryLine: "डिब्बे से",
    familyPotNote: "वही हांडी, बच्चे के लिए हल्की.",
    kitchenLine: "तेज़ शाम का नाश्ता, चावल के विकल्प, और घर की चीज़ों से 10 मिनट का खाना.",
    emptyKitchenList: "इस रसोई के लिए यह सूची खाली है. दूसरी समस्या देखें.",
    snacksThisWeek: "इस हफ़्ते के स्नैक्स",
    stepOf: "चरण",
    of: "/",
    field: "फ़ील्ड",
    yourAnswer: "आपका जवाब",
    name: "नाम",
    age: "उम्र",
    gender: "लिंग",
    boy: "लड़का",
    girl: "लड़की",
    other: "अन्य",
    ageRange: "केवल 4–12 साल",
    genderHint: "लड़का या लड़की",
    optionalHw: "कद और वज़न — तुलना",
    hwMain: "पार्क वाली तुलना",
    hwLede: "उसी उम्र के दूसरे बच्चे लंबे या भारी लग सकते हैं. अपने बच्चे का कद और वज़न लिखें. सामान्य पट्टी देखें. फिर ऊर्जा, प्रोटीन, कैल्शियम की थाली लिखते हैं.",
    hwBand: "इस उम्र का सामान्य",
    hwSkip: "आज फीता नहीं? खाली छोड़ें, बाद में जोड़ें.",
    heightCm: "ऊंचाई सेमी",
    weightKg: "वज़न किग्रा",
    anyAllergies: "कोई एलर्जी? (वैकल्पिक)",
    foodsAvoid: "बचने वाले खाद्य (वैकल्पिक)",
    foodsAvoidPh: "जैसे मशरूम, करेला",
    namePh: "जैसे आन्या, रोहन…",
    choice: "चुनाव",
    now: "अभी",
    diet: "आहार",
    style: "शैली",
    dietHome: "घर का आहार",
    regionStyle: "क्षेत्रीय शैली",
    veg: "शाकाहारी",
    egg: "अंडाशाकाहारी",
    nonveg: "मांसाहारी",
    south: "दक्षिण भारतीय",
    north: "उत्तर भारतीय",
    mixed: "मिश्रित",
    vegHint: "पौधे आधारित",
    eggHint: "अंडा शामिल",
    nonvegHint: "मांस शामिल",
    southHint: "डोसा, सांभर, चावल",
    northHint: "रोटी, पराठा, दाल",
    mixedHint: "दोनों से",
    challengeTick: "इस महीने मेज़ पर जो सच है, सब चुनें. एक से ज़्यादा ठीक है.",
    pickyHint: "नया खाना मना करता है",
    underHint: "ज़्यादा कैलोरी चाहिए",
    vegSkipHint: "सब्ज़ी छोड़ता है",
    readyFor: "तैयार",
    seeTable: "सूची देखें",
    continue: "जारी रखें",
    back: "वापस",
    saving: "सहेज रहे हैं…",
    yourChild: "आपका बच्चा",
    years: "साल",
    enterName: "बच्चे का नाम लिखें",
    pickChallenge: "कम से कम एक कठिनाई चुनें",
    selectChallenge: "कम से कम एक कठिनाई चुनें",
    signInToSave: "प्रोफ़ाइल सहेजने के लिए साइन इन करें",
    nextReadTable: "अब बच्चे को सामान्य कद–वज़न पट्टी के पास रखते हैं. फिर आज रात की थाली और फ्रिज PDF.",
    allergyDairy: "दूध",
    allergyNuts: "मेवे",
    allergyEggs: "अंडे",
    allergyGluten: "ग्लूटेन / गेहूँ",
    allergySoy: "सोया",
    allergySeafood: "मछली / समुद्री भोजन",
    chUnder: "कम वज़न",
    chAppetite: "कम भूख",
    chPicky: "नखरेबाज़",
    chVeg: "सब्ज़ी पसंद नहीं",
    chMilk: "दूध नहीं पीता",
    chEnergy: "कम ऊर्जा",
    chSports: "खेलकूद वाला बच्चा",
    goalHealthy: "स्वस्थ पोषण",
    goalHabits: "बेहतर खाने की आदत",
    goalProtein: "प्रोटीन पर ध्यान",
    goalBalance: "संतुलित भोजन",
    goalVariety: "ज़्यादा विविधता",
    roomToday: "आज",
    roomWeek: "इस हफ्ते",
    roomMonth: "30 दिन",
    monthHint: "हर दिन एक दोपहर का खाना। पाँच थालियों के लिए दिन पर टैप करें।",
    roomGoals: "लक्ष्य",
    morningSnack: "सुबह का नाश्ता",
    eveningSnack: "शाम का नाश्ता",
    kcal: "कैलोरी",
    nutrient: "पोषक",
    thisWeek: "इस हफ्ते",
    target: "लक्ष्य",
    day: "दिन",
    date: "तारीख",
    meal: "खाना",
    whyHere: "यह क्यों है",
    rows: "पंक्ति",
    focusIron: "आयरन",
    focusCalcium: "कैल्शियम",
    focusProtein: "प्रोटीन",
    focusFiber: "फाइबर",
    focusEnergy: "ऊर्जा",
    compareKicker: "BabyBite के साथ · बिना अनुमान",
    compareTitle: "घर पर दो शामें",
    compareBody:
      "तस्वीर कहानी कहती है. BabyBite के साथ: स्वस्थ खाना, चार्ट पर विकास, बेहतर आदतें, खुश बच्चा. बिना योजना: खाने का अटकल, कोई ट्रैकिंग नहीं, छूटे बदलाव, फर्श पर चिंता. BabyBite बाएँ पक्ष पर — भारतीय थाली, कद–वज़न नोट, केवल शैक्षिक मार्गदर्शन.",
    otherTable: "दूसरा बच्चा",
    thisTable: "BabyBite के साथ",
    otherLine1: "उसी उम्र में लंबा लगता है",
    otherLine2: "ज़्यादा वज़न. स्कूल के बाद ज़्यादा ऊर्जा.",
    otherLine3: "घर आकर तुलना करती हैं",
    thisLine1: "मेज़ पर स्वस्थ खाना",
    thisLine2: "चार्ट पर विकास देखें",
    thisLine3: "बेहतर आदतें · खुश बच्चा",
    compareNote:
      "आज स्वस्थ खाना — कल उज्ज्वल कल. केवल शैक्षिक मार्गदर्शन — अतिरिक्त सेंटीमीटर कद का वादा नहीं.",
    momCompareAlt:
      "दो हिस्सों वाली तस्वीर: BabyBite के साथ खुश माँ–बच्चा और विकास चार्ट; बिना योजना चिंतित माँ",
    artCompareScenePark: "पार्क",
    artCompareBridgePark: "एक ही कक्षा, एक उम्र — दूसरा बच्चा लंबा लगता है.",
    artCompareSceneRelative: "रिश्तेदार",
    artCompareBridgeRelative: "मिलने पर सवाल. घर आकर नापती हैं.",
    artCompareSceneWorry: "चिंता",
    artCompareBridgeWorry: "BabyBite कद और वज़न लिखकर भारतीय थालियाँ बनाता है.",
    growthKicker: "कद और वज़न",
    growthTitle: "सामान्य पट्टी के पास आपका बच्चा",
    growthBody:
      "माँएँ यहीं इसलिए रुकती हैं. इस उम्र का सामान्य कद और वज़न देखें. थाली ऊर्जा, प्रोटीन, कैल्शियम देती है ताकि शरीर बढ़े. अतिरिक्त सेंटीमीटर का वादा नहीं.",
    usualHeight: "सामान्य कद पट्टी",
    usualWeight: "सामान्य वज़न पट्टी",
    measured: "आपने लिखा",
    noExtraCm: "अतिरिक्त सेंटीमीटर नहीं. खाना, नींद और खेल बढ़ाते हैं.",
    energyPlate: "थाली में ऊर्जा",
    proteinPlate: "थाली में प्रोटीन",
    calciumPlate: "थाली में कैल्शियम",
    artTiffin: "चावल, दाल और सब्ज़ी वाला पीला टिफिन",
    artHeroDinner: "माँ सोच रही है आज रात क्या बनाएँ",
    artBondMotherChild: "माँ और बच्चा साथ में मेज़ पर बैठे हैं",
    artTiffins: "हफ़्ते की पाँच भारतीय टिफिन थालियाँ",
    artNutrients: "एक थाली में प्रोटीन, आयरन, कैल्शियम, ऊर्जा",
    artFeeding: "मेज़ पर बच्चे को खाना खिलाती माँ",
    artMark: "बच्चा, किताब, और आज रात की थाली",
    artCompare: "मेज़ पर थका बच्चा, फिर खाना, नींद और खेल से ऊर्जा वाला बच्चा",
    showcaseKicker: "आज रात इस टेबल पर",
    whyTonight: "यह रात क्यों",
    otherKids: "दूसरे बच्चे आज रात",
    yourKitchen: "इस महीने यह रसोई",
    lightMode: "उजाला",
    darkMode: "अँधेरा",
    tryAgain: "फिर कोशिश करें",
    goHome: "होम",
    myPlan: "मेरी योजना",
    pageMissing: "वह पेज टेबल पर नहीं है.",
    holdOn: "रुकिए",
    dinnerThatWay: "वापस आइए. रात का खाना इसी तरफ़ है.",
    oauthFail: "Google साइन-इन पूरा नहीं हुआ. कनेक्शन देखकर फिर कोशिश करें.",
    badLogin: "ईमेल या पासवर्ड गलत है",
    acceptTerms: "आगे बढ़ने के लिए नियम स्वीकार करें",
    signupFail: "खाता नहीं बन सका",
    emailTaken: "इस ईमेल का खाता पहले से है. साइन इन करें.",
    createdSignIn: "खाता बन गया. साइन इन करें.",
    welcomeBite: "BabyBite में स्वागत है",
    couldNotLoad: "यह पेज नहीं खुल सका",
    finishStep: "आज रात की थाली खोलने के लिए यह कदम पूरा करें.",
    signInFirst: "पहले साइन इन करें और ऑनबोर्डिंग पूरी करें",
    analysisNote: "थालियाँ वही मानती हैं जो आपने बताया. 30 दिन और फ्रिज PDF अगला कदम है.",
    fridgeNext: "आगे फ्रिज PDF",
    payCalendar: "30 दिन भारतीय भोजन, टेबल दोहराए बिना",
    payRhythm: "नाश्ता, दो स्नैक, दोपहर, रात — 4–12 हिस्सा",
    payFridge: "आपकी ऑनबोर्डिंग से बना प्रिंट कॉपी",
    payNotes: "प्रोटीन, आयरन, कैल्शियम, फाइबर — रसोई की भाषा में",
    payGrowth: "बच्चे की उम्र की कद–वज़न पट्टी, फिर बढ़ने वाली थाली",
    eduOnly: "केवल शैक्षिक मार्गदर्शन — चिकित्सा सलाह नहीं.",
    writingPlate: "आज रात की थाली लिख रहे हैं…",
    lostTitle: "गुम",
    settingsTitle: "बच्चा और रसोई",
    appearance: "दिखावट",
    appearanceHint: "उजाला या अँधेरा",
    profileSaved: "प्रोफ़ाइल सहेजी गई",
    saveProfile: "प्रोफ़ाइल सहेजें",
    planRebuilt: "भोजन योजना फिर लिखी गई",
    rebuildPlan: "योजना फिर लिखें",
    rebuilding: "फिर लिख रहे हैं…",
    account: "खाता",
    goalHealthyHint: "संतुलित भारतीय भोजन, उम्र के हिस्से, दिन में पाँच समय.",
    goalHabitsHint: "शांत टेबल समय. स्नैक और रात जाने-पहचाने समय पर.",
    goalProteinHint: "दाल, पनीर, अंडे, अंकुर — आपकी रसोई में प्रोटीन.",
    goalBalanceHint: "चावल, दाल, सब्ज़ी, चर्बी एक थाली में — बड़ों की थाली नहीं.",
    goalVarietyHint: "नए अनाज और सब्ज़ी, ताकि नखरेबाज़ बच्चे फिर देखें.",
    failedPlan: "भोजन योजना नहीं खुल सकी",
    failedAnalysis: "टेबल पढ़ाई नहीं खुल सकी",
    failedSettings: "सेटिंग नहीं खुल सकी",
    calendar: "कैलेंडर",
    rhythm: "ताल",
    notes: "नोट",
    invalidEmail: "सही ईमेल लिखें",
    downloadPdf: "PDF डाउनलोड करें",
    sendPdfEmail: "विवरण मेल पर भेजें",
    resendPdfEmail: "मेल फिर भेजें",
    downloading: "डाउनलोड हो रहा है…",
    sendingEmail: "भेज रहे हैं…",
    pdfSent: "PDF आपके ईमेल पर भेजा गया",
    pdfDownloadFail: "PDF डाउनलोड नहीं हो सका",
    pdfSendFail: "ईमेल पर PDF नहीं भेजा जा सका",
    genericApiError: "कुछ गलत हुआ. फिर कोशिश करें.",
    allergyNoPrefix: "नहीं",
    avoidFood: "बचें",
    logOut: "लॉग आउट",
    loggingOut: "बाहर जा रहे हैं…",
    setChild: "बच्चा",
    setKitchen: "रसोई",
    setFocus: "ध्यान",
    setPlan: "भोजन पैक",
    setPlanNote: "फ्रिज PDF डाउनलोड करें, या इस रसोई से 30 दिन फिर लिखें।",
    signedInAs: "साइन इन हैं",
    setLede: "बच्चे या रसोई को बदलें. जब हो जाए, सहेजें.",
    pickOne: "एक चुनें",
    unsavedHint: "अभी सेव नहीं हुआ",
    unsavedLeave: "बदलाव सेव नहीं हैं. फिर भी लॉग आउट करें?",
    saveChanges: "बदलाव सहेजें",
    savedNeedRebuild: "सेव हो गया. इस रसोई के हिसाब से 30 दिन फिर लिखें.",
    payKicker: "30 दिन खोलें",
    payTitle: "आज रात लिखी गई",
    payOff: "80% छूट",
    payJust: "30 दिन और फ्रिज PDF के लिए ₹159",
    payMethod: "भुगतान",
    payCard: "कार्ड",
    payUpi: "UPI",
    payNowBtn: "₹159 दें",
    paying: "पक्का कर रहे हैं…",
    processing: "प्रोसेस हो रहा है...",
    done: "हो गया",
    paySecure: "तीस दिन और फ्रिज PDF इसी कदम के बाद।",
    cardNumber: "कार्ड नंबर",
    cardExpiry: "समाप्ति",
    cardCvv: "CVV",
    cardHint: "आगे बढ़ने के लिए कार्ड लिखें",
    upiId: "UPI आईडी",
    upiHint: "आगे बढ़ने के लिए UPI आईडी लिखें",
    successKicker: "लिख दिया",
    successTitle: "बढ़ने के साल",
    successPeak: "कद बढ़ने का समय",
    successLead: "स्कूल के सालों में कद सबसे तेज़ बढ़ता है.",
    successBody:
      "फ्रिज PDF ऊर्जा, प्रोटीन, कैल्शियम मानती है ताकि शरीर खुद बढ़े. अतिरिक्त सेंटीमीटर का वादा नहीं.",
    successWriting: "30 दिन लिख रहे हैं…",
    trustLine: "4–12 साल के लिए लिखा. केवल शैक्षिक. बढ़त की चिंता हो तो अपने बाल रोग विशेषज्ञ से पूछें.",
    firstNoted: "पहली नोट",
    nowNoted: "अब",
    remeasureHint: "30 दिन बाद फिर लिखें. पहली, अब, और सामान्य पट्टी मिलाएँ. अतिरिक्त सेंटीमीटर का वादा नहीं.",
    addChild: "एक और बच्चा जोड़ें",
    switchChild: "किसकी रसोई?",
  },
} as const;

export type MotherCopyKey = keyof (typeof COPY)["en"];

export function motherCopy(lang: MotherLang, key: MotherCopyKey): string {
  return COPY[lang][key] ?? COPY.en[key];
}

export function translateCta(lang: MotherLang, english: string): string {
  const map: Record<string, MotherCopyKey> = {
    "Make a plan for my child": "makePlan",
    "I already have an account": "haveAccount",
    "Continue your child’s details": "continueChild",
    "Get the fridge PDF": "fridgePdf",
    "Open tonight’s meals": "openTonight",
    "Child & kitchen": "childKitchen",
    "Show my 30 days": "showThirty",
  };
  const key = map[english];
  return key ? motherCopy(lang, key) : english;
}

export const HTML_LANG: Record<MotherLang, string> = {
  en: "en",
  ta: "ta",
  hi: "hi",
};

const SLOT_KEYS = {
  breakfast: "breakfast",
  morningSnack: "morningSnack",
  lunch: "lunch",
  eveningSnack: "eveningSnack",
  dinner: "dinnerIs",
} as const;

export function mealSlotCopy(lang: MotherLang, slot: MealSlot, opts?: { packable?: boolean }): string {
  if (opts?.packable && slot === "lunch") {
    return motherCopy(lang, "packableLunch");
  }
  return motherCopy(lang, SLOT_KEYS[slot]);
}
