import type { MealSlot } from "@/types/kidfuel";

export type MotherLang = "en" | "ta" | "hi";

export const MOTHER_LANGS: { id: MotherLang; short: string; label: string }[] = [
  { id: "en", short: "EN", label: "English" },
  { id: "ta", short: "த", label: "Tamil" },
  { id: "hi", short: "हिं", label: "Hindi" },
];

const COPY = {
  en: {
    makePlan: "Make a plan for my child",
    haveAccount: "I already have an account",
    seeHow: "See how it looks",
    tonight: "Tonight",
    forYou: "For you",
    also: "Also",
    later: "Later",
    you: "You",
    signIn: "Sign in",
    childKitchen: "Child & kitchen",
    showThirty: "Show my 30 days",
    openTonight: "Open tonight’s meals",
    continueChild: "Continue your child’s details",
    fridgePdf: "Get the fridge PDF",
    whatsapp: "Send on WhatsApp",
    grocery: "Keep at home today",
    dinnerIs: "Dinner",
    breakfast: "Breakfast",
    lunch: "Lunch",
    snack: "Snack",
    sampleCaption: "Indian meals for mothers of kids 4–12",
    sampleFor: "For a 7-year-old. South Indian kitchen.",
    writingDinner: "Writing tonight’s plate…",
    planReady: "Tonight is ready",
    table: "Table",
    why: "Why",
    whatsDinner: "What’s for dinner?",
    ourPlates: "The plates",
    howTitle: "How dinner gets decided",
    step1: "Tell us how you cook",
    step1Body: "Age 4–12, kitchen, allergies. Five minutes. Then we stay in your home food.",
    step2: "Tonight is written",
    step2Body: "Breakfast through dinner, rotated so the table does not repeat itself.",
    step3: "Tape the fridge PDF",
    step3Body: "Thirty days on paper. WhatsApp tonight. No 7pm question.",
    noSeven: "No 7pm question",
    bandBody: "Thirty days of Indian meals. Tape the fridge. WhatsApp tonight.",
    footerTag: "For mothers of kids 4–12",
    duoKicker: "From the kitchen",
    duoTitle: "Breakfast, then lunch",
    bondKicker: "Amma and child",
    bondTitle: "Dinner is how you hold them",
    bondBody:
      "After school, the question is always the same. BabyBite writes the plate so you can sit down, look at them, and eat together.",
    bondTag: "We eat together",
    menuTag: "Indian meals for mothers of kids 4–12.",
    stickerTonight: "Tonight",
    stickerAges: "Ages 4–12",
    stickerKitchen: "Indian kitchen",
    stickerFridge: "Fridge PDF",
    stickerSimple: "Keep it simple",
    stickerProtein: "Protein",
    stickerPicky: "Picky eater?",
    stickerSchool: "School lunch",
    stickerSeven: "7pm, sorted",
    stickerGrains: "Ragi · Dal · Curd",
    stickerRegion: "South · North · Mixed",
    stickerDinnerQ: "What’s for dinner?",
    welcomeBack: "Welcome back",
    createAccount: "Create your account",
    authNote: "Indian plates for mothers of kids 4–12.",
    fullName: "Full name",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm password",
    passwordHint: "8+ characters with letters and numbers",
    createAccountBtn: "Create account",
    creating: "Creating…",
    signingIn: "Signing in…",
    or: "Or",
    continueGoogle: "Continue with Google",
    reviewTerms: "Review Terms & Conditions",
    haveAccountQ: "Have an account?",
    noAccount: "No account?",
    createOne: "Create one",
    acceptedTermsNote:
      "You accepted our Terms & Conditions (education only — consult your doctor for medical decisions).",
    termsTitle: "Terms & Conditions",
    termsSub: "For mothers of kids 4–12",
    termsRequired: "Required before signup",
    termsScroll: "Scroll to the bottom to continue",
    termsDecline: "Decline",
    termsAgree: "I agree — create account",
    termsVersion: "Version",
    closeMenu: "Close menu",
    openMenu: "Open menu",
    language: "Language",
    obTitle1: "Tell us about your child",
    obTitle2: "How you cook at home",
    obTitle3: "What feels hard at the table",
    obTitle4: "What you want this month",
    obTitle5: "We’ll build from this",
    obLede1: "Name, age, and allergies first — we portion for 4–12, never an adult thali.",
    obLede2: "Vegetarian, eggs, or non-veg; South, North, or mixed. We stay in your kitchen.",
    obLede3: "Picky eating, skipped vegetables, low energy: tick what is true this month.",
    obLede4: "One focus for the next 30 days. The PDF and the meals follow this choice.",
    obLede5: "Check the picture. Next we read the table — then tonight’s plates and the fridge PDF.",
    roomChild: "Child",
    roomFood: "Food",
    roomChallenges: "Challenges",
    roomGoal: "Goal",
    roomReview: "Review",
    stepOf: "Step",
    of: "of",
    field: "Field",
    yourAnswer: "Your answer",
    name: "Name",
    age: "Age",
    gender: "Gender",
    boy: "Boy",
    girl: "Girl",
    other: "Other",
    optionalHw: "Optional height & weight",
    heightCm: "Height cm",
    weightKg: "Weight kg",
    anyAllergies: "Any allergies? (optional)",
    foodsAvoid: "Foods to avoid (optional)",
    foodsAvoidPh: "e.g. mushroom, bitter gourd",
    namePh: "e.g. Aanya, Rohan…",
    choice: "Choice",
    now: "Now",
    diet: "Diet",
    style: "Style",
    dietHome: "Diet at home",
    regionStyle: "Regional style",
    veg: "Vegetarian",
    egg: "Eggetarian",
    nonveg: "Non-veg",
    south: "South Indian",
    north: "North Indian",
    mixed: "Mixed",
    vegHint: "Plant-based meals",
    eggHint: "Includes eggs",
    nonvegHint: "Includes meat",
    southHint: "Dosa, sambar, rice",
    northHint: "Roti, paratha, dal",
    mixedHint: "Best of both",
    challengeTick: "Tick everything that is true at your table this month. More than one is fine.",
    pickyHint: "Refuses new foods",
    underHint: "Needs more calories",
    vegSkipHint: "Skips veggies",
    readyFor: "Ready for",
    seeTable: "See the table",
    continue: "Continue",
    back: "Back",
    saving: "Saving…",
    yourChild: "Your child",
    years: "years",
    enterName: "Enter your child's name",
    pickChallenge: "Pick at least one challenge",
    selectChallenge: "Select at least one challenge",
    signInToSave: "Sign in to save your profile",
    nextReadTable: "Next we read the table. Tonight’s plates and the fridge PDF follow from this.",
    allergyDairy: "Dairy",
    allergyNuts: "Tree nuts",
    allergyEggs: "Eggs",
    allergyGluten: "Gluten / wheat",
    allergySoy: "Soy",
    allergySeafood: "Fish / seafood",
    chUnder: "Underweight",
    chAppetite: "Poor appetite",
    chPicky: "Picky eater",
    chVeg: "Doesn't like vegetables",
    chMilk: "Doesn't drink milk",
    chEnergy: "Low energy",
    chSports: "Active sports child",
    goalHealthy: "Healthy nutrition",
    goalHabits: "Better eating habits",
    goalProtein: "Protein focus",
    goalBalance: "Balanced meals",
    goalVariety: "Improved food variety",
    roomToday: "Today",
    roomWeek: "This week",
    roomMonth: "30 days",
    monthHint: "One dinner per day. Tap a day for breakfast through dinner.",
    roomGoals: "Goals",
    morningSnack: "Morning snack",
    eveningSnack: "Evening snack",
    kcal: "kcal",
    nutrient: "Nutrient",
    thisWeek: "This week",
    target: "Target",
    day: "Day",
    date: "Date",
    meal: "Meal",
    whyHere: "Why it is here",
    rows: "Rows",
    focusIron: "Iron",
    focusCalcium: "Calcium",
    focusProtein: "Protein",
    focusFiber: "Fiber",
    focusEnergy: "Energy",
    compareKicker: "Other tables tonight",
    compareTitle: "Other kids already sat down",
    compareBody:
      "At 7pm, some 4–12 tables already have dal, egg, or ragi. The 7pm question is still open at yours. BabyBite writes the plate so your child sits, eats, and grows from the kitchen you already have.",
    otherTable: "The other table",
    thisTable: "Your table with BabyBite",
    otherLine1: "Still asking what’s for dinner",
    otherLine2: "Leftover rice. No protein on the plate.",
    otherLine3: "Height and weight left to chance",
    thisLine1: "Egg dosa is already written",
    thisLine2: "Dal, curd, ragi — protein and calcium",
    thisLine3: "The fridge PDF follows the growing body",
    compareNote: "Educational guidance only. We do not promise extra centimetres of height.",
    growthKicker: "Height and weight",
    growthTitle: "What this kitchen is for",
    growthBody:
      "Children this age sit in a usual height and weight band. These plates fill energy, protein, and calcium so the body can do its own growing. Not a promise of extra centimetres.",
    usualHeight: "Usual height band",
    usualWeight: "Usual weight band",
    measured: "You noted",
    noExtraCm: "Not extra centimetres. Food, sleep, and play do the growing.",
    energyPlate: "Energy on the plate",
    proteinPlate: "Protein on the plate",
    calciumPlate: "Calcium on the plate",
    artTiffin: "Yellow tiffin with rice, dal, and vegetables",
    artTiffins: "Five Indian tiffin plates for the week",
    artNutrients: "Protein, iron, calcium, and energy on one plate",
    artMark: "A child, a book, and tonight’s plate",
    artCompare: "A tired child at the table, then a child with energy from food, sleep, and play",
    showcaseKicker: "Tonight at this table",
    whyTonight: "Why this dinner",
    otherKids: "Other kids tonight",
    yourKitchen: "This kitchen this month",
    lightMode: "Light",
    darkMode: "Dark",
    tryAgain: "Try again",
    goHome: "Home",
    myPlan: "My plan",
    pageMissing: "That page isn’t on the table.",
    holdOn: "Hold on",
    dinnerThatWay: "Head back. Dinner is still this way.",
    oauthFail: "Google sign-in could not finish. Check your connection and try again.",
    badLogin: "Invalid email or password",
    acceptTerms: "Please accept the Terms & Conditions to continue",
    signupFail: "Could not create the account",
    createdSignIn: "Account created. Please sign in.",
    welcomeBite: "Welcome to BabyBite",
    couldNotLoad: "Could not load this page",
    finishStep: "Finish this step to open tonight’s meals.",
    signInFirst: "Sign in and complete onboarding first",
    analysisNote: "The plates follow what you told us. Thirty days and a fridge PDF come after this step.",
    fridgeNext: "Fridge PDF next",
    payCalendar: "Thirty days of Indian meals, rotated so the table does not repeat itself",
    payRhythm: "Breakfast, two snacks, lunch, and dinner — portions for ages 4–12",
    payFridge: "The print copy, built from the onboarding you just finished",
    payNotes: "Protein, iron, calcium, and fibre explained in kitchen language",
    eduOnly: "Educational guidance only — not medical advice.",
    writingPlate: "Writing tonight’s plate…",
    lostTitle: "Lost",
    settingsTitle: "Child & kitchen",
    appearance: "Appearance",
    appearanceHint: "Light or dark",
    profileSaved: "Profile saved",
    saveProfile: "Save profile",
    planRebuilt: "Meal plan rebuilt",
    rebuildPlan: "Rebuild meal plan",
    rebuilding: "Rebuilding…",
    account: "Account",
    goalHealthyHint: "Balanced Indian meals, age portions, five slots a day.",
    goalHabitsHint: "A calmer table rhythm. Snacks and dinner at a known time.",
    goalProteinHint: "Dal, paneer, eggs, sprouts — protein in the kitchen you already have.",
    goalBalanceHint: "Rice, dal, vegetable, and fat in one plate, not an adult thali.",
    goalVarietyHint: "New grains and vegetables, rotated so picky eaters see them again.",
    failedPlan: "Could not load the meal plan",
    failedAnalysis: "Could not load the table reading",
    failedSettings: "Could not load settings",
    calendar: "Calendar",
    rhythm: "Rhythm",
    notes: "Notes",
    invalidEmail: "Enter a valid email",
    downloadPdf: "Download PDF",
    sendPdfEmail: "Send details on mail",
    resendPdfEmail: "Resend the mail",
    downloading: "Downloading…",
    sendingEmail: "Sending…",
    pdfSent: "PDF sent to your email",
    pdfDownloadFail: "Could not download the PDF",
    logOut: "Log out",
    loggingOut: "Signing out…",
    setChild: "Child",
    setKitchen: "Kitchen",
    setFocus: "Focus",
    setPlan: "Meal pack",
    setPlanNote: "Download the fridge PDF, or rewrite the 30 days from this kitchen.",
    signedInAs: "Signed in",
    setLede: "Change the child or the kitchen. Save when you are done.",
    pickOne: "Pick one",
    unsavedHint: "Not saved yet",
    unsavedLeave: "Your changes are not saved. Log out anyway?",
    saveChanges: "Save changes",
    savedNeedRebuild: "Saved. Rewrite the 30 days so dinner matches this kitchen.",
    payKicker: "Unlock the 30 days",
    payTitle: "Tonight, written",
    payOff: "80% off",
    payJust: "Just ₹159",
    payMethod: "Pay with",
    payCard: "Card",
    payUpi: "UPI",
    payNowBtn: "Pay ₹159",
    paying: "Confirming…",
    paySecure: "Thirty days and the fridge PDF after this step.",
    cardNumber: "Card number",
    cardExpiry: "Expiry",
    cardCvv: "CVV",
    cardHint: "Enter the card details to continue",
    upiId: "UPI ID",
    upiHint: "Enter a UPI ID to continue",
    successKicker: "It's written",
    successTitle: "The growing years",
    successPeak: "Peak growing years",
    successLead: "Height climbs fastest in these school years.",
    successBody:
      "The fridge PDF follows energy, protein, and calcium so the body can do its own growing. Educational guidance only — not extra centimetres promised.",
    successWriting: "Writing the 30 days…",
  },
  ta: {
    makePlan: "என் குழந்தைக்கு உணவுத் திட்டம்",
    haveAccount: "எனக்கு கணக்கு உள்ளது",
    seeHow: "எப்படி இருக்கும் என்று பார்",
    tonight: "இன்று இரவு",
    forYou: "உங்களுக்கு",
    also: "இன்னும்",
    later: "பிறகு",
    you: "நீங்கள்",
    signIn: "உள்நுழை",
    childKitchen: "குழந்தை & சமையல்",
    showThirty: "30 நாள் திட்டத்தைக் காட்டு",
    openTonight: "இன்றிரவு உணவைத் திற",
    continueChild: "குழந்தை விவரங்களைத் தொடர்",
    fridgePdf: "ஃபிரிட்ஜ் PDF பெறு",
    whatsapp: "WhatsApp-ல் அனுப்பு",
    grocery: "இன்று வீட்டில் வைத்திருங்கள்",
    dinnerIs: "இரவு உணவு",
    breakfast: "காலை உணவு",
    lunch: "மதிய உணவு",
    snack: "சிற்றுண்டி",
    sampleCaption: "4–12 வயது குழந்தைகளுக்கான இந்திய உணவு",
    sampleFor: "7 வயது. தென் இந்திய சமையல்.",
    writingDinner: "இன்றிரவு தட்டு எழுதப்படுகிறது…",
    planReady: "இன்றிரவு தயார்",
    table: "பட்டியல்",
    why: "ஏன்",
    whatsDinner: "இன்றிரவு என்ன?",
    ourPlates: "தட்டுகள்",
    howTitle: "இரவு உணவு எப்படி முடிவு ஆகும்",
    step1: "எப்படி சமைக்கிறீர்கள் என்று சொல்லுங்கள்",
    step1Body: "4–12 வயது, சமையல், ஒவ்வாமை. ஐந்து நிமிடம். பிறகு உங்கள் வீட்டு உணவிலேயே.",
    step2: "இன்றிரவு எழுதப்பட்டுவிட்டது",
    step2Body: "காலை முதல் இரவு வரை. மேசை மீண்டும் மீண்டும் ஆகாது.",
    step3: "ஃபிரிட்ஜ் PDF ஒட்டுங்கள்",
    step3Body: "30 நாள் காகிதத்தில். இன்றிரவை WhatsApp-ல். 7 மணி கேள்வி இல்லை.",
    noSeven: "மாலை 7 கேள்வி இல்லை",
    bandBody: "30 நாள் இந்திய உணவு. ஃபிரிட்ஜ் PDF. இன்றிரவை WhatsApp-ல்.",
    footerTag: "4–12 வயது குழந்தைகளின் தாய்மார்களுக்கு",
    duoKicker: "சமையலறையில் இருந்து",
    duoTitle: "காலை, பிறகு மதியம்",
    bondKicker: "அம்மாவும் குழந்தையும்",
    bondTitle: "இரவு உணவுதான் அணைப்பு",
    bondBody:
      "பள்ளிக்குப் பிறகு கேள்வி ஒன்றுதான். BabyBite தட்டை எழுதும். நீங்கள் உட்கார்ந்து, அவர்களைப் பார்த்து, சேர்ந்து சாப்பிடுங்கள்.",
    bondTag: "சேர்ந்து சாப்பிடுவோம்",
    menuTag: "4–12 வயது குழந்தைகளுக்கான இந்திய உணவு.",
    stickerTonight: "இன்று இரவு",
    stickerAges: "4–12 வயது",
    stickerKitchen: "இந்திய சமையல்",
    stickerFridge: "ஃபிரிட்ஜ் PDF",
    stickerSimple: "எளிதாக வையுங்கள்",
    stickerProtein: "புரதம்",
    stickerPicky: "சாப்பாடு பிடிக்காதா?",
    stickerSchool: "பள்ளி மதிய உணவு",
    stickerSeven: "மாலை 7 முடிந்தது",
    stickerGrains: "ராகி · பருப்பு · தயிர்",
    stickerRegion: "தெற்கு · வடக்கு · கலவை",
    stickerDinnerQ: "இன்றிரவு என்ன?",
    welcomeBack: "மீண்டும் வருக",
    createAccount: "கணக்கை உருவாக்குங்கள்",
    authNote: "4–12 வயது குழந்தைகளுக்கான இந்திய தட்டு.",
    fullName: "முழுப் பெயர்",
    email: "மின்னஞ்சல்",
    password: "கடவுச்சொல்",
    confirmPassword: "கடவுச்சொல்லை உறுதிப்படுத்து",
    passwordHint: "8+ எழுத்துகள், எழுத்தும் எண்ணும்",
    createAccountBtn: "கணக்கை உருவாக்கு",
    creating: "உருவாக்குகிறது…",
    signingIn: "உள்நுழைகிறது…",
    or: "அல்லது",
    continueGoogle: "Google-ல் தொடரவும்",
    reviewTerms: "விதிமுறைகளை மீண்டும் பார்",
    haveAccountQ: "கணக்கு உள்ளதா?",
    noAccount: "கணக்கு இல்லையா?",
    createOne: "ஒன்றை உருவாக்கு",
    acceptedTermsNote:
      "விதிமுறைகளை ஏற்றுக்கொண்டீர்கள் (கல்வி மட்டும் — மருத்துவ முடிவுக்கு மருத்துவரை அணுகுங்கள்).",
    termsTitle: "விதிமுறைகள்",
    termsSub: "4–12 வயது குழந்தைகளின் தாய்மார்களுக்கு",
    termsRequired: "பதிவுக்கு முன் தேவை",
    termsScroll: "தொடர கீழே நகர்த்துங்கள்",
    termsDecline: "மறு",
    termsAgree: "ஏற்கிறேன் — கணக்கு உருவாக்கு",
    termsVersion: "பதிப்பு",
    closeMenu: "மெனுவை மூடு",
    openMenu: "மெனுவை திற",
    language: "மொழி",
    obTitle1: "உங்கள் குழந்தையைச் சொல்லுங்கள்",
    obTitle2: "வீட்டில் எப்படி சமைக்கிறீர்கள்",
    obTitle3: "மேசையில் எது கடினம்",
    obTitle4: "இந்த மாதம் என்ன வேண்டும்",
    obTitle5: "இதிலிருந்து எழுதுவோம்",
    obLede1: "பெயர், வயது, ஒவ்வாமை முதலில் — 4–12 வயது பங்கு. பெரியவர் தட்டு அல்ல.",
    obLede2: "சைவம், முட்டை, அல்லது அசைவம். தெற்கு, வடக்கு, அல்லது கலவை. உங்கள் சமையலே.",
    obLede3: "சாப்பாடு பிடிக்காதது, காய்கறி தவிர்ப்பது, சோர்வு: இந்த மாதம் உண்மையானதைத் தேர்வு.",
    obLede4: "அடுத்த 30 நாளுக்கு ஒரே கவனம். PDF-ம் உணவும் இதைப் பின்பற்றும்.",
    obLede5: "படத்தைப் பாருங்கள். அடுத்து பட்டியல் — பிறகு இன்றிரவு தட்டும் ஃபிரிட்ஜ் PDF-ம்.",
    roomChild: "குழந்தை",
    roomFood: "உணவு",
    roomChallenges: "சிக்கல்கள்",
    roomGoal: "இலக்கு",
    roomReview: "சரிபார்",
    stepOf: "படி",
    of: "/",
    field: "புலம்",
    yourAnswer: "உங்கள் பதில்",
    name: "பெயர்",
    age: "வயது",
    gender: "பாலினம்",
    boy: "ஆண்",
    girl: "பெண்",
    other: "மற்றவை",
    optionalHw: "உயரம் & எடை (விருப்பம்)",
    heightCm: "உயரம் செ.மீ",
    weightKg: "எடை கி.கி",
    anyAllergies: "ஒவ்வாமை உள்ளதா? (விருப்பம்)",
    foodsAvoid: "தவிர்க்க வேண்டிய உணவு (விருப்பம்)",
    foodsAvoidPh: "எ.கா. காளான், பாகற்காய்",
    namePh: "எ.கா. ஆன்யா, ரோகன்…",
    choice: "தேர்வு",
    now: "இப்போது",
    diet: "உணவு முறை",
    style: "பாணி",
    dietHome: "வீட்டு உணவு",
    regionStyle: "பிராந்திய பாணி",
    veg: "சைவம்",
    egg: "முட்டை சைவம்",
    nonveg: "அசைவம்",
    south: "தென் இந்திய",
    north: "வட இந்திய",
    mixed: "கலவை",
    vegHint: "தாவர உணவு",
    eggHint: "முட்டை உண்டு",
    nonvegHint: "இறைச்சி உண்டு",
    southHint: "தோசை, சாம்பார், சோறு",
    northHint: "ரோட்டி, பராத்தா, பருப்பு",
    mixedHint: "இரண்டும்",
    challengeTick: "இந்த மாதம் மேசையில் உண்மையானதை எல்லாம் தேர்வு. ஒன்றுக்கு மேல் சரி.",
    pickyHint: "புதிய உணவை மறுக்கும்",
    underHint: "அதிக கலோரி தேவை",
    vegSkipHint: "காய்கறி தவிர்க்கும்",
    readyFor: "தயார்",
    seeTable: "பட்டியலைப் பார்",
    continue: "தொடர்",
    back: "பின்",
    saving: "சேமிக்கிறது…",
    yourChild: "உங்கள் குழந்தை",
    years: "வயது",
    enterName: "குழந்தையின் பெயரை உள்ளிடுங்கள்",
    pickChallenge: "ஒரு சிக்கலாவது தேர்வு",
    selectChallenge: "ஒரு சிக்கலாவது தேர்வு",
    signInToSave: "சுயவிவரத்தைச் சேமிக்க உள்நுழையுங்கள்",
    nextReadTable: "அடுத்து பட்டியல். இன்றிரவு தட்டும் ஃபிரிட்ஜ் PDF-ம் இதிலிருந்து.",
    allergyDairy: "பால்",
    allergyNuts: "கொட்டைகள்",
    allergyEggs: "முட்டை",
    allergyGluten: "கோதுமை / குளுட்டன்",
    allergySoy: "சோயா",
    allergySeafood: "மீன் / கடல் உணவு",
    chUnder: "எடை குறைவு",
    chAppetite: "பசி குறைவு",
    chPicky: "சாப்பாடு பிடிக்காது",
    chVeg: "காய்கறி பிடிக்காது",
    chMilk: "பால் குடிக்காது",
    chEnergy: "சோர்வு",
    chSports: "விளையாட்டு குழந்தை",
    goalHealthy: "ஆரோக்கிய ஊட்டம்",
    goalHabits: "நல்ல உணவு பழக்கம்",
    goalProtein: "புரத கவனம்",
    goalBalance: "சமநிலை உணவு",
    goalVariety: "உணவு வகை அதிகம்",
    roomToday: "இன்று",
    roomWeek: "இந்த வாரம்",
    roomMonth: "30 நாள்",
    monthHint: "ஒரு நாளுக்கு ஒரு இரவு உணவு. ஐந்து தட்டுகளுக்கும் ஒரு நாளைத் தட்டவும்.",
    roomGoals: "இலக்கு",
    morningSnack: "காலை சிற்றுண்டி",
    eveningSnack: "மாலை சிற்றுண்டி",
    kcal: "கலோரி",
    nutrient: "ஊட்டம்",
    thisWeek: "இந்த வாரம்",
    target: "இலக்கு",
    day: "நாள்",
    date: "தேதி",
    meal: "உணவு",
    whyHere: "ஏன் இங்கே",
    rows: "வரிசை",
    focusIron: "இரும்பு",
    focusCalcium: "கால்சியம்",
    focusProtein: "புரதம்",
    focusFiber: "நார்",
    focusEnergy: "ஆற்றல்",
    compareKicker: "மற்ற மேசைகள் இன்றிரவு",
    compareTitle: "மற்ற குழந்தைகள் ஏற்கனவே அமர்ந்தனர்",
    compareBody:
      "இரவு 7 மணிக்கு சில 4–12 மேசைகளில் பருப்பு, முட்டை, ராகி ஏற்கனவே இருக்கும். உங்கள் மேசையில் இன்னும் 7 மணி கேள்வி. BabyBite தட்டை எழுதும் — உங்கள் சமையலறையிலேயே குழந்தை அமர்ந்து சாப்பிட்டு வளரும்.",
    otherTable: "மற்ற மேசை",
    thisTable: "BabyBite உடன் உங்கள் மேசை",
    otherLine1: "இன்னும் என்ன சாப்பாடு என்று கேட்கிறீர்கள்",
    otherLine2: "மீதி சோறு. தட்டில் புரதம் இல்லை.",
    otherLine3: "உயரம், எடை வாய்ப்புக்கே விடப்பட்டது",
    thisLine1: "முட்டை தோசை ஏற்கனவே எழுதப்பட்டது",
    thisLine2: "பருப்பு, தயிர், ராகி — புரதம் மற்றும் கால்சியம்",
    thisLine3: "ஃபிரிட்ஜ் PDF வளரும் உடலைப் பின்தொடரும்",
    compareNote: "கல்வி வழிகாட்டுதல் மட்டும். கூடுதல் சென்டிமீட்டர் உயரம் வாக்குறுதி இல்லை.",
    growthKicker: "உயரம் மற்றும் எடை",
    growthTitle: "இந்த சமையலறை எதற்காக",
    growthBody:
      "இந்த வயது குழந்தைகள் ஒரு வழக்கமான உயரம்–எடை வரம்பில் இருக்கிறார்கள். இந்த தட்டுகள் ஆற்றல், புரதம், கால்சியம் நிரப்பும். கூடுதல் சென்டிமீட்டர் வாக்குறுதி இல்லை.",
    usualHeight: "வழக்கமான உயரம்",
    usualWeight: "வழக்கமான எடை",
    measured: "நீங்கள் குறித்தது",
    noExtraCm: "கூடுதல் சென்டிமீட்டர் இல்லை. உணவு, தூக்கம், விளையாட்டு வளர்க்கும்.",
    energyPlate: "தட்டில் ஆற்றல்",
    proteinPlate: "தட்டில் புரதம்",
    calciumPlate: "தட்டில் கால்சியம்",
    artTiffin: "சாதம், பருப்பு, காய்கறி உள்ள மஞ்சள் டிப்பின்",
    artTiffins: "வாரத்துக்கு ஐந்து இந்திய டிப்பின் தட்டுகள்",
    artNutrients: "ஒரு தட்டில் புரதம், இரும்பு, கால்சியம், ஆற்றல்",
    artMark: "குழந்தை, புத்தகம், இன்றிரவு தட்டு",
    artCompare: "மேசையில் சோர்வான குழந்தை, பிறகு உணவு, தூக்கம், விளையாட்டால் ஆற்றல் பெற்ற குழந்தை",
    showcaseKicker: "இன்றிரவு இந்த மேசையில்",
    whyTonight: "இந்த இரவு ஏன்",
    otherKids: "மற்ற குழந்தைகள் இன்றிரவு",
    yourKitchen: "இந்த மாதம் இந்த சமையலறை",
    lightMode: "வெளிச்சம்",
    darkMode: "இருள்",
    tryAgain: "மீண்டும் முயலவும்",
    goHome: "முகப்பு",
    myPlan: "என் திட்டம்",
    pageMissing: "அந்த பக்கம் மேசையில் இல்லை.",
    holdOn: "சற்று பொறுங்கள்",
    dinnerThatWay: "திரும்பி வாருங்கள். இரவு உணவு இந்த வழியில்தான்.",
    oauthFail: "Google உள்நுழைவு முடியவில்லை. இணைப்பைப் பார்த்து மீண்டும் முயலவும்.",
    badLogin: "மின்னஞ்சல் அல்லது கடவுச்சொல் தவறு",
    acceptTerms: "தொடர விதிமுறைகளை ஏற்கவும்",
    signupFail: "கணக்கு உருவாக்க முடியவில்லை",
    createdSignIn: "கணக்கு உருவானது. உள்நுழையவும்.",
    welcomeBite: "BabyBite-க்கு வரவேற்கிறோம்",
    couldNotLoad: "இந்த பக்கத்தை ஏற்ற முடியவில்லை",
    finishStep: "இன்றிரவு உணவைத் திறக்க இந்த படியை முடிக்கவும்.",
    signInFirst: "முதலில் உள்நுழைந்து ஆன்போர்டிங் முடிக்கவும்",
    analysisNote: "நீங்கள் சொன்னதையே தட்டுகள் பின்பற்றும். 30 நாள் மற்றும் ஃபிரிட்ஜ் PDF அடுத்த படி.",
    fridgeNext: "அடுத்து ஃபிரிட்ஜ் PDF",
    payCalendar: "30 நாள் இந்திய உணவு, மேசை மீளாமல் சுழலும்",
    payRhythm: "காலை உணவு, இரண்டு சிற்றுண்டி, மதியம், இரவு — 4–12 பங்கு",
    payFridge: "நீங்கள் முடித்த ஆன்போர்டிங்கிலிருந்து அச்சிடும் நகல்",
    payNotes: "புரதம், இரும்பு, கால்சியம், நார் — சமையலறை மொழியில்",
    eduOnly: "கல்வி வழிகாட்டுதல் மட்டும் — மருத்துவ ஆலோசனை அல்ல.",
    writingPlate: "இன்றிரவு தட்டை எழுதுகிறோம்…",
    lostTitle: "காணவில்லை",
    settingsTitle: "குழந்தை மற்றும் சமையலறை",
    appearance: "தோற்றம்",
    appearanceHint: "வெளிச்சம் அல்லது இருள்",
    profileSaved: "சுயவிவரம் சேமிக்கப்பட்டது",
    saveProfile: "சுயவிவரம் சேமி",
    planRebuilt: "உணவுத் திட்டம் மீண்டும் எழுதப்பட்டது",
    rebuildPlan: "திட்டத்தை மீண்டும் எழுது",
    rebuilding: "மீண்டும் எழுதுகிறோம்…",
    account: "கணக்கு",
    goalHealthyHint: "சமநிலை இந்திய உணவு, வயது பங்கு, நாளைக்கு ஐந்து நேரம்.",
    goalHabitsHint: "அமைதியான மேசை நேரம். சிற்றுண்டி மற்றும் இரவு தெரிந்த நேரத்தில்.",
    goalProteinHint: "பருப்பு, பனீர், முட்டை, முளை — உங்கள் சமையலறையிலேயே புரதம்.",
    goalBalanceHint: "சோறு, பருப்பு, காய்கறி, கொழுப்பு ஒரே தட்டில் — பெரியவர் தட்டு அல்ல.",
    goalVarietyHint: "புதிய தானியம், காய்கறி — பிடிக்காத குழந்தை மீண்டும் பார்க்கும்.",
    failedPlan: "உணவுத் திட்டத்தை ஏற்ற முடியவில்லை",
    failedAnalysis: "மேசை வாசிப்பை ஏற்ற முடியவில்லை",
    failedSettings: "அமைப்புகளை ஏற்ற முடியவில்லை",
    calendar: "நாட்காட்டி",
    rhythm: "தாளம்",
    notes: "குறிப்பு",
    invalidEmail: "சரியான மின்னஞ்சல் எழுதவும்",
    downloadPdf: "PDF பதிவிறக்கு",
    sendPdfEmail: "விவரங்களை மின்னஞ்சலில் அனுப்பு",
    resendPdfEmail: "மின்னஞ்சலை மீண்டும் அனுப்பு",
    downloading: "பதிவிறக்குகிறோம்…",
    sendingEmail: "அனுப்புகிறோம்…",
    pdfSent: "PDF உங்கள் மின்னஞ்சலுக்கு அனுப்பப்பட்டது",
    pdfDownloadFail: "PDF பதிவிறக்க முடியவில்லை",
    logOut: "வெளியேறு",
    loggingOut: "வெளியேறுகிறோம்…",
    setChild: "குழந்தை",
    setKitchen: "சமையலறை",
    setFocus: "கவனம்",
    setPlan: "உணவுப் பொதி",
    setPlanNote: "ஃபிரிட்ஜ் PDF பதிவிறக்குங்கள், அல்லது இந்த சமையலறையிலிருந்து 30 நாளை மீண்டும் எழுதுங்கள்.",
    signedInAs: "உள்நுழைந்துள்ளீர்கள்",
    setLede: "குழந்தை அல்லது சமையலறையை மாற்றுங்கள். முடிந்ததும் சேமியுங்கள்.",
    pickOne: "ஒன்றைத் தேர்வு",
    unsavedHint: "இன்னும் சேமிக்கவில்லை",
    unsavedLeave: "மாற்றங்கள் சேமிக்கப்படவில்லை. இப்படியே வெளியேறவா?",
    saveChanges: "மாற்றங்களைச் சேமி",
    savedNeedRebuild: "சேமித்தோம். இந்த சமையலறைக்கு ஏற்ப 30 நாளை மீண்டும் எழுதுங்கள்.",
    payKicker: "30 நாளைத் திற",
    payTitle: "இன்றிரவு எழுதப்பட்டது",
    payOff: "80% தள்ளுபடி",
    payJust: "வெறும் ₹159",
    payMethod: "செலுத்த",
    payCard: "அட்டை",
    payUpi: "UPI",
    payNowBtn: "₹159 செலுத்து",
    paying: "உறுதி செய்கிறோம்…",
    paySecure: "30 நாள் உணவும் ஃபிரிட்ஜ் PDF-ம் இந்த அடியில்.",
    cardNumber: "அட்டை எண்",
    cardExpiry: "காலம்",
    cardCvv: "CVV",
    cardHint: "தொடர அட்டை விவரங்களை எழுதவும்",
    upiId: "UPI ஐடி",
    upiHint: "தொடர UPI ஐடி எழுதவும்",
    successKicker: "எழுதப்பட்டது",
    successTitle: "வளரும் ஆண்டுகள்",
    successPeak: "உயரம் வளரும் காலம்",
    successLead: "பள்ளி ஆண்டுகளில் உயரம் வேகமாக ஏறும்.",
    successBody:
      "ஃபிரிட்ஜ் PDF ஆற்றல், புரதம், கால்சியத்தைப் பின்பற்றும். உடல் தானே வளரும். கூடுதல் சென்டிமீட்டர் வாக்குறுதி இல்லை.",
    successWriting: "30 நாளை எழுதுகிறோம்…",
  },
  hi: {
    makePlan: "मेरे बच्चे की योजना बनाएँ",
    haveAccount: "मेरा खाता पहले से है",
    seeHow: "कैसा दिखता है, देखें",
    tonight: "आज रात",
    forYou: "आपके लिए",
    also: "और भी",
    later: "बाद में",
    you: "आप",
    signIn: "साइन इन",
    childKitchen: "बच्चा और रसोई",
    showThirty: "30 दिन की योजना दिखाएँ",
    openTonight: "आज रात की थाली खोलें",
    continueChild: "बच्चे की जानकारी जारी रखें",
    fridgePdf: "फ्रिज PDF लें",
    whatsapp: "WhatsApp पर भेजें",
    grocery: "आज घर पर रखें",
    dinnerIs: "रात का खाना",
    breakfast: "नाश्ता",
    lunch: "दोपहर का खाना",
    snack: "नाश्ता",
    sampleCaption: "4–12 साल के बच्चों के लिए भारतीय भोजन",
    sampleFor: "7 साल. दक्षिण भारतीय रसोई.",
    writingDinner: "आज रात की थाली लिखी जा रही है…",
    planReady: "आज रात तैयार है",
    table: "सूची",
    why: "क्यों",
    whatsDinner: "आज रात क्या है?",
    ourPlates: "थाली",
    howTitle: "रात का खाना कैसे तय होता है",
    step1: "बताएँ आप कैसे पकाती हैं",
    step1Body: "उम्र 4–12, रसोई, एलर्जी. पाँच मिनट. फिर आपके घर का खाना ही.",
    step2: "आज रात लिखी जा चुकी है",
    step2Body: "नाश्ते से रात तक. मेज़ दोहराती नहीं.",
    step3: "फ्रिज PDF चिपकाएँ",
    step3Body: "तीस दिन कागज पर. आज रात WhatsApp पर. शाम सात का सवाल नहीं.",
    noSeven: "शाम सात का सवाल नहीं",
    bandBody: "तीस दिन भारतीय भोजन. फ्रिज PDF. आज रात WhatsApp पर.",
    footerTag: "4–12 साल के बच्चों की माँओं के लिए",
    duoKicker: "रसोई से",
    duoTitle: "नाश्ता, फिर दोपहर",
    bondKicker: "माँ और बच्चा",
    bondTitle: "रात का खाना ही गोद है",
    bondBody:
      "स्कूल के बाद सवाल वही रहता है. BabyBite थाली लिख देता है, ताकि आप बैठें, उन्हें देखें, और साथ खाएँ.",
    bondTag: "हम साथ खाते हैं",
    menuTag: "4–12 साल के बच्चों के लिए भारतीय भोजन.",
    stickerTonight: "आज रात",
    stickerAges: "उम्र 4–12",
    stickerKitchen: "भारतीय रसोई",
    stickerFridge: "फ्रिज PDF",
    stickerSimple: "सरल रखें",
    stickerProtein: "प्रोटीन",
    stickerPicky: "खाना पसंद नहीं?",
    stickerSchool: "स्कूल लंच",
    stickerSeven: "शाम 7 तय",
    stickerGrains: "रागी · दाल · दही",
    stickerRegion: "दक्षिण · उत्तर · मिश्रित",
    stickerDinnerQ: "आज रात क्या है?",
    welcomeBack: "वापस स्वागत है",
    createAccount: "खाता बनाएँ",
    authNote: "4–12 साल के बच्चों के लिए भारतीय थाली.",
    fullName: "पूरा नाम",
    email: "ईमेल",
    password: "पासवर्ड",
    confirmPassword: "पासवर्ड पुष्टि",
    passwordHint: "8+ अक्षर, अक्षर और अंक",
    createAccountBtn: "खाता बनाएँ",
    creating: "बन रहा है…",
    signingIn: "साइन इन हो रहा है…",
    or: "या",
    continueGoogle: "Google से जारी रखें",
    reviewTerms: "नियम फिर देखें",
    haveAccountQ: "खाता है?",
    noAccount: "खाता नहीं?",
    createOne: "एक बनाएँ",
    acceptedTermsNote:
      "आपने नियम स्वीकार किए (केवल शिक्षा — चिकित्सा निर्णय के लिए डॉक्टर से पूछें).",
    termsTitle: "नियम और शर्तें",
    termsSub: "4–12 साल के बच्चों की माँओं के लिए",
    termsRequired: "साइन अप से पहले ज़रूरी",
    termsScroll: "आगे बढ़ने के लिए नीचे स्क्रॉल करें",
    termsDecline: "अस्वीकार",
    termsAgree: "मैं सहमत हूँ — खाता बनाएँ",
    termsVersion: "संस्करण",
    closeMenu: "मेनू बंद करें",
    openMenu: "मेनू खोलें",
    language: "भाषा",
    obTitle1: "अपने बच्चे के बारे में बताएँ",
    obTitle2: "घर पर कैसे पकाती हैं",
    obTitle3: "मेज़ पर क्या कठिन है",
    obTitle4: "इस महीने क्या चाहिए",
    obTitle5: "इसी से लिखेंगे",
    obLede1: "पहले नाम, उम्र, एलर्जी — हिस्से 4–12 के लिए. वयस्क थाली नहीं.",
    obLede2: "शाकाहारी, अंडा, या मांसाहारी. दक्षिण, उत्तर, या मिश्रित. आपकी रसोई ही.",
    obLede3: "नखरे, सब्ज़ी छोड़ना, थकान: इस महीने जो सच है, चुनें.",
    obLede4: "अगले 30 दिन का एक ध्यान. PDF और खाना इसी को मानेंगे.",
    obLede5: "तस्वीर देखें. फिर सूची — फिर आज रात की थाली और फ्रिज PDF.",
    roomChild: "बच्चा",
    roomFood: "खाना",
    roomChallenges: "कठिनाई",
    roomGoal: "लक्ष्य",
    roomReview: "जाँच",
    stepOf: "चरण",
    of: "/",
    field: "फ़ील्ड",
    yourAnswer: "आपका जवाब",
    name: "नाम",
    age: "उम्र",
    gender: "लिंग",
    boy: "लड़का",
    girl: "लड़की",
    other: "अन्य",
    optionalHw: "ऊंचाई और वज़न (वैकल्पिक)",
    heightCm: "ऊंचाई सेमी",
    weightKg: "वज़न किग्रा",
    anyAllergies: "कोई एलर्जी? (वैकल्पिक)",
    foodsAvoid: "बचने वाले खाद्य (वैकल्पिक)",
    foodsAvoidPh: "जैसे मशरूम, करेला",
    namePh: "जैसे आन्या, रोहन…",
    choice: "चुनाव",
    now: "अभी",
    diet: "आहार",
    style: "शैली",
    dietHome: "घर का आहार",
    regionStyle: "क्षेत्रीय शैली",
    veg: "शाकाहारी",
    egg: "अंडाशाकाहारी",
    nonveg: "मांसाहारी",
    south: "दक्षिण भारतीय",
    north: "उत्तर भारतीय",
    mixed: "मिश्रित",
    vegHint: "पौधे आधारित",
    eggHint: "अंडा शामिल",
    nonvegHint: "मांस शामिल",
    southHint: "डोसा, सांभर, चावल",
    northHint: "रोटी, पराठा, दाल",
    mixedHint: "दोनों से",
    challengeTick: "इस महीने मेज़ पर जो सच है, सब चुनें. एक से ज़्यादा ठीक है.",
    pickyHint: "नया खाना मना करता है",
    underHint: "ज़्यादा कैलोरी चाहिए",
    vegSkipHint: "सब्ज़ी छोड़ता है",
    readyFor: "तैयार",
    seeTable: "सूची देखें",
    continue: "जारी रखें",
    back: "वापस",
    saving: "सहेज रहे हैं…",
    yourChild: "आपका बच्चा",
    years: "साल",
    enterName: "बच्चे का नाम लिखें",
    pickChallenge: "कम से कम एक कठिनाई चुनें",
    selectChallenge: "कम से कम एक कठिनाई चुनें",
    signInToSave: "प्रोफ़ाइल सहेजने के लिए साइन इन करें",
    nextReadTable: "अब सूची पढ़ते हैं. आज रात की थाली और फ्रिज PDF इसी से आते हैं.",
    allergyDairy: "दूध",
    allergyNuts: "मेवे",
    allergyEggs: "अंडे",
    allergyGluten: "ग्लूटेन / गेहूँ",
    allergySoy: "सोया",
    allergySeafood: "मछली / समुद्री भोजन",
    chUnder: "कम वज़न",
    chAppetite: "कम भूख",
    chPicky: "नखरेबाज़",
    chVeg: "सब्ज़ी पसंद नहीं",
    chMilk: "दूध नहीं पीता",
    chEnergy: "कम ऊर्जा",
    chSports: "खेलकूद वाला बच्चा",
    goalHealthy: "स्वस्थ पोषण",
    goalHabits: "बेहतर खाने की आदत",
    goalProtein: "प्रोटीन पर ध्यान",
    goalBalance: "संतुलित भोजन",
    goalVariety: "ज़्यादा विविधता",
    roomToday: "आज",
    roomWeek: "इस हफ्ते",
    roomMonth: "30 दिन",
    monthHint: "हर दिन एक रात का खाना। पाँच थालियों के लिए दिन पर टैप करें।",
    roomGoals: "लक्ष्य",
    morningSnack: "सुबह का नाश्ता",
    eveningSnack: "शाम का नाश्ता",
    kcal: "कैलोरी",
    nutrient: "पोषक",
    thisWeek: "इस हफ्ते",
    target: "लक्ष्य",
    day: "दिन",
    date: "तारीख",
    meal: "खाना",
    whyHere: "यह क्यों है",
    rows: "पंक्ति",
    focusIron: "आयरन",
    focusCalcium: "कैल्शियम",
    focusProtein: "प्रोटीन",
    focusFiber: "फाइबर",
    focusEnergy: "ऊर्जा",
    compareKicker: "दूसरे टेबल आज रात",
    compareTitle: "दूसरे बच्चे पहले ही बैठ चुके",
    compareBody:
      "शाम सात बजे कुछ 4–12 टेबल पर दाल, अंडा या रागी पहले से है. आपके टेबल पर अभी सात बजे का सवाल है. BabyBite थाली लिखता है ताकि बच्चा बैठे, खाए, और आपके ही रसोई से बढ़े.",
    otherTable: "दूसरा टेबल",
    thisTable: "BabyBite के साथ आपका टेबल",
    otherLine1: "अभी भी पूछ रहे हैं रात को क्या है",
    otherLine2: "बचा भात. थाली में प्रोटीन नहीं.",
    otherLine3: "कद और वज़न संयोग पर छूट गए",
    thisLine1: "अंडा डोसा पहले से लिखा है",
    thisLine2: "दाल, दही, रागी — प्रोटीन और कैल्शियम",
    thisLine3: "फ्रिज PDF बढ़ते शरीर के साथ चलती है",
    compareNote: "केवल शैक्षिक मार्गदर्शन. अतिरिक्त सेंटीमीटर कद का वादा नहीं.",
    growthKicker: "कद और वज़न",
    growthTitle: "यह रसोई किस लिए है",
    growthBody:
      "इस उम्र के बच्चे एक सामान्य कद–वज़न पट्टी में बैठते हैं. ये थालियाँ ऊर्जा, प्रोटीन, कैल्शियम भरती हैं ताकि शरीर खुद बढ़े. अतिरिक्त सेंटीमीटर का वादा नहीं.",
    usualHeight: "सामान्य कद पट्टी",
    usualWeight: "सामान्य वज़न पट्टी",
    measured: "आपने लिखा",
    noExtraCm: "अतिरिक्त सेंटीमीटर नहीं. खाना, नींद और खेल बढ़ाते हैं.",
    energyPlate: "थाली में ऊर्जा",
    proteinPlate: "थाली में प्रोटीन",
    calciumPlate: "थाली में कैल्शियम",
    artTiffin: "चावल, दाल और सब्ज़ी वाला पीला टिफिन",
    artTiffins: "हफ़्ते की पाँच भारतीय टिफिन थालियाँ",
    artNutrients: "एक थाली में प्रोटीन, आयरन, कैल्शियम, ऊर्जा",
    artMark: "बच्चा, किताब, और आज रात की थाली",
    artCompare: "मेज़ पर थका बच्चा, फिर खाना, नींद और खेल से ऊर्जा वाला बच्चा",
    showcaseKicker: "आज रात इस टेबल पर",
    whyTonight: "यह रात क्यों",
    otherKids: "दूसरे बच्चे आज रात",
    yourKitchen: "इस महीने यह रसोई",
    lightMode: "उजाला",
    darkMode: "अँधेरा",
    tryAgain: "फिर कोशिश करें",
    goHome: "होम",
    myPlan: "मेरी योजना",
    pageMissing: "वह पेज टेबल पर नहीं है.",
    holdOn: "रुकिए",
    dinnerThatWay: "वापस आइए. रात का खाना इसी तरफ़ है.",
    oauthFail: "Google साइन-इन पूरा नहीं हुआ. कनेक्शन देखकर फिर कोशिश करें.",
    badLogin: "ईमेल या पासवर्ड गलत है",
    acceptTerms: "आगे बढ़ने के लिए नियम स्वीकार करें",
    signupFail: "खाता नहीं बन सका",
    createdSignIn: "खाता बन गया. साइन इन करें.",
    welcomeBite: "BabyBite में स्वागत है",
    couldNotLoad: "यह पेज नहीं खुल सका",
    finishStep: "आज रात की थाली खोलने के लिए यह कदम पूरा करें.",
    signInFirst: "पहले साइन इन करें और ऑनबोर्डिंग पूरी करें",
    analysisNote: "थालियाँ वही मानती हैं जो आपने बताया. 30 दिन और फ्रिज PDF अगला कदम है.",
    fridgeNext: "आगे फ्रिज PDF",
    payCalendar: "30 दिन भारतीय भोजन, टेबल दोहराए बिना",
    payRhythm: "नाश्ता, दो स्नैक, दोपहर, रात — 4–12 हिस्सा",
    payFridge: "आपकी ऑनबोर्डिंग से बना प्रिंट कॉपी",
    payNotes: "प्रोटीन, आयरन, कैल्शियम, फाइबर — रसोई की भाषा में",
    eduOnly: "केवल शैक्षिक मार्गदर्शन — चिकित्सा सलाह नहीं.",
    writingPlate: "आज रात की थाली लिख रहे हैं…",
    lostTitle: "गुम",
    settingsTitle: "बच्चा और रसोई",
    appearance: "दिखावट",
    appearanceHint: "उजाला या अँधेरा",
    profileSaved: "प्रोफ़ाइल सहेजी गई",
    saveProfile: "प्रोफ़ाइल सहेजें",
    planRebuilt: "भोजन योजना फिर लिखी गई",
    rebuildPlan: "योजना फिर लिखें",
    rebuilding: "फिर लिख रहे हैं…",
    account: "खाता",
    goalHealthyHint: "संतुलित भारतीय भोजन, उम्र के हिस्से, दिन में पाँच समय.",
    goalHabitsHint: "शांत टेबल समय. स्नैक और रात जाने-पहचाने समय पर.",
    goalProteinHint: "दाल, पनीर, अंडे, अंकुर — आपकी रसोई में प्रोटीन.",
    goalBalanceHint: "चावल, दाल, सब्ज़ी, चर्बी एक थाली में — बड़ों की थाली नहीं.",
    goalVarietyHint: "नए अनाज और सब्ज़ी, ताकि नखरेबाज़ बच्चे फिर देखें.",
    failedPlan: "भोजन योजना नहीं खुल सकी",
    failedAnalysis: "टेबल पढ़ाई नहीं खुल सकी",
    failedSettings: "सेटिंग नहीं खुल सकी",
    calendar: "कैलेंडर",
    rhythm: "ताल",
    notes: "नोट",
    invalidEmail: "सही ईमेल लिखें",
    downloadPdf: "PDF डाउनलोड करें",
    sendPdfEmail: "विवरण मेल पर भेजें",
    resendPdfEmail: "मेल फिर भेजें",
    downloading: "डाउनलोड हो रहा है…",
    sendingEmail: "भेज रहे हैं…",
    pdfSent: "PDF आपके ईमेल पर भेजा गया",
    pdfDownloadFail: "PDF डाउनलोड नहीं हो सका",
    logOut: "लॉग आउट",
    loggingOut: "बाहर जा रहे हैं…",
    setChild: "बच्चा",
    setKitchen: "रसोई",
    setFocus: "ध्यान",
    setPlan: "भोजन पैक",
    setPlanNote: "फ्रिज PDF डाउनलोड करें, या इस रसोई से 30 दिन फिर लिखें।",
    signedInAs: "साइन इन हैं",
    setLede: "बच्चे या रसोई को बदलें. जब हो जाए, सहेजें.",
    pickOne: "एक चुनें",
    unsavedHint: "अभी सेव नहीं हुआ",
    unsavedLeave: "बदलाव सेव नहीं हैं. फिर भी लॉग आउट करें?",
    saveChanges: "बदलाव सहेजें",
    savedNeedRebuild: "सेव हो गया. इस रसोई के हिसाब से 30 दिन फिर लिखें.",
    payKicker: "30 दिन खोलें",
    payTitle: "आज रात लिखी गई",
    payOff: "80% छूट",
    payJust: "सिर्फ़ ₹159",
    payMethod: "भुगतान",
    payCard: "कार्ड",
    payUpi: "UPI",
    payNowBtn: "₹159 दें",
    paying: "पक्का कर रहे हैं…",
    paySecure: "तीस दिन और फ्रिज PDF इसी कदम के बाद।",
    cardNumber: "कार्ड नंबर",
    cardExpiry: "समाप्ति",
    cardCvv: "CVV",
    cardHint: "आगे बढ़ने के लिए कार्ड लिखें",
    upiId: "UPI आईडी",
    upiHint: "आगे बढ़ने के लिए UPI आईडी लिखें",
    successKicker: "लिख दिया",
    successTitle: "बढ़ने के साल",
    successPeak: "कद बढ़ने का समय",
    successLead: "स्कूल के सालों में कद सबसे तेज़ बढ़ता है.",
    successBody:
      "फ्रिज PDF ऊर्जा, प्रोटीन, कैल्शियम मानती है ताकि शरीर खुद बढ़े. अतिरिक्त सेंटीमीटर का वादा नहीं.",
    successWriting: "30 दिन लिख रहे हैं…",
  },
} as const;

export type MotherCopyKey = keyof (typeof COPY)["en"];

export function motherCopy(lang: MotherLang, key: MotherCopyKey): string {
  return COPY[lang][key] ?? COPY.en[key];
}

export function translateCta(lang: MotherLang, english: string): string {
  const map: Record<string, MotherCopyKey> = {
    "Make a plan for my child": "makePlan",
    "I already have an account": "haveAccount",
    "Continue your child’s details": "continueChild",
    "Get the fridge PDF": "fridgePdf",
    "Open tonight’s meals": "openTonight",
    "Child & kitchen": "childKitchen",
    "Show my 30 days": "showThirty",
  };
  const key = map[english];
  return key ? motherCopy(lang, key) : english;
}

export const HTML_LANG: Record<MotherLang, string> = {
  en: "en",
  ta: "ta",
  hi: "hi",
};

const SLOT_KEYS = {
  breakfast: "breakfast",
  morningSnack: "morningSnack",
  lunch: "lunch",
  eveningSnack: "eveningSnack",
  dinner: "dinnerIs",
} as const;

export function mealSlotCopy(lang: MotherLang, slot: MealSlot): string {
  return motherCopy(lang, SLOT_KEYS[slot]);
}
